export const businessSoftwareKeywordPages = [
  {
    slug: "business-software-solutions", title: "Business Software Solutions", keyword: "business software solutions", path: "/business-software-solutions/", hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Software category / connected operations",
    description: "Explore business software solutions by connecting a clear operating need to the routines, people and information a system must support.", lead: "Business software solutions are most useful when they support a complete operating need rather than a disconnected feature. Start by mapping the work, the hand-offs and the evidence that would show a better system is helping.", decision: "What operating need should a business software solution make easier to manage from start to finish?",
    signals: [{ label: "NEED", value: "Map the operation" }, { label: "FLOW", value: "Check the connections" }, { label: "FIT", value: "Test the routine" }], checkpoints: [{ title: "Define the operating need", detail: "Name the business outcome and recurring process the system must improve." }, { title: "Trace the connections", detail: "Follow the information, people and hand-offs around the work." }, { title: "Test a useful outcome", detail: "Use a real scenario to see whether the solution improves the full routine." }], related: [{ title: "Business software", path: "/business-software/" }, { title: "Small business software", path: "/small-business-software/" }, { title: "Business management software", path: "/business-management-software/" }],
  },
  {
    slug: "cloud-business-software", title: "Cloud Business Software", keyword: "cloud business software", path: "/cloud-business-software/", hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Software category / shared access",
    description: "Explore cloud business software by assessing the work, access, information and shared routines it needs to support.", lead: "Cloud business software can make work more accessible and connected when the right people can find the right information at the right point in the process. Assess access, ownership and the practical workflow together.", decision: "What shared business routine needs accessible information without losing ownership or oversight?",
    signals: [{ label: "ACCESS", value: "Set the right roles" }, { label: "CONTEXT", value: "Keep information connected" }, { label: "REVIEW", value: "Check the workflow" }], checkpoints: [{ title: "Clarify roles and access", detail: "Identify who needs to see, update or approve information in the routine." }, { title: "Follow the working context", detail: "Check how records, messages and decisions move between people." }, { title: "Test the everyday experience", detail: "Use a real process to verify the system is workable for the team." }], related: [{ title: "Business software", path: "/business-software/" }, { title: "Business software solutions", path: "/business-software-solutions/" }, { title: "Software for small business", path: "/software-for-small-business/" }],
  },
  {
    slug: "software-for-small-business", title: "Software for Small Business", keyword: "software for small business", path: "/software-for-small-business/", hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Software category / practical fit",
    description: "Explore software for small business by starting with the daily work, available capacity and practical outcomes that matter most.", lead: "Software for small business should make an important routine more manageable without creating a heavier setup to maintain. Focus on a useful starting point, the people involved and the outcome you need to see in day-to-day work.", decision: "Which everyday business task needs a simpler, more reliable way of being completed?",
    signals: [{ label: "TASK", value: "Choose the important work" }, { label: "CAPACITY", value: "Keep the change workable" }, { label: "RESULT", value: "Check the outcome" }], checkpoints: [{ title: "Prioritise the important task", detail: "Select the routine where a clearer process would create a visible benefit." }, { title: "Keep implementation realistic", detail: "Consider the time, people and support available for a change." }, { title: "Review the complete process", detail: "Test the option with the real work and follow-up it needs to support." }], related: [{ title: "Business software", path: "/business-software/" }, { title: "Small business software", path: "/small-business-software/" }, { title: "Business productivity software", path: "/business-productivity-software/" }],
  },
  {
    slug: "business-productivity-software", title: "Business Productivity Software", keyword: "business productivity software", path: "/business-productivity-software/", hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Software category / productive routines",
    description: "Explore business productivity software by identifying repeated friction, shared work and the next action a system should make easier.", lead: "Business productivity software earns its place when it reduces avoidable effort from recurring work and makes ownership easier to see. Begin with the routine where information, tasks or follow-up are currently getting in the way.", decision: "Which repeated business routine would benefit from clearer ownership and less avoidable effort?",
    signals: [{ label: "FRICTION", value: "Find the drag" }, { label: "DEFAULT", value: "Make work visible" }, { label: "IMPROVE", value: "Keep the useful change" }], checkpoints: [{ title: "Trace the source of friction", detail: "Follow a recurring task and identify where work waits, repeats or becomes unclear." }, { title: "Make the next action visible", detail: "Check how people can see ownership, context and status." }, { title: "Review the change", detail: "Keep only the workflow changes that make the work easier to complete well." }], related: [{ title: "Business software", path: "/business-software/" }, { title: "Business management software", path: "/business-management-software/" }, { title: "Small business software", path: "/small-business-software/" }],
  },
  {
    slug: "business-management-software", title: "Business Management Software", keyword: "business management software", path: "/business-management-software/", hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Software category / operating visibility",
    description: "Explore business management software through the planning, people, information and operating routines it needs to make visible.", lead: "Business management software should help a team see how work is planned, owned and reviewed across an operation. Map the decision points, records and responsibilities that matter before comparing systems.", decision: "What part of the operation needs a clearer view of work, information and responsibility?",
    signals: [{ label: "OPERATE", value: "Map the business routine" }, { label: "OWN", value: "Make responsibility clear" }, { label: "REVIEW", value: "See the next decision" }], checkpoints: [{ title: "Map the operating rhythm", detail: "Identify the recurring work, decisions and reporting that hold the process together." }, { title: "Clarify responsibility", detail: "Check who owns each action, review point and important record." }, { title: "Test the management view", detail: "Use a realistic operating scenario to assess visibility and fit." }], related: [{ title: "Business software", path: "/business-software/" }, { title: "Business software solutions", path: "/business-software-solutions/" }, { title: "Business productivity software", path: "/business-productivity-software/" }],
  },
];
