import type { CalculatorKind } from "@/components/CalculatorPanel";

export type CalculatorDefinition = { slug: string; kind: CalculatorKind; title: string; detail: string; path: string; description: string; assumptions: string[] };

const assumptions = {
  vat: ["The calculator uses the tax rate entered; it does not select a rate for you.", "Results are rounded for display.", "This is a planning calculation, not tax advice or return preparation."],
  margin: ["Profit is revenue minus cost.", "Margin is profit divided by revenue, expressed as a percentage.", "The result does not account for omitted costs, tax or timing."],
  breakEven: ["Contribution per unit is price minus variable cost per unit.", "The unit result is rounded up to a whole unit.", "It assumes the entered price, cost and fixed-cost figures remain constant."],
  freelance: ["Available billing days equal working days minus holiday days.", "The calculation adds annual expenses to desired income.", "It does not calculate tax, pension, sick leave, sales time or unpaid work."],
  salary: ["The calculation divides the annual amount by the working time entered.", "It is an indicative gross figure and does not calculate deductions.", "Use it as a planning starting point rather than employment advice."],
  takeHome: ["Net amount is gross income less the percentage deduction entered.", "It does not calculate current tax, payroll, benefits or location-specific deductions.", "Use it as a planning estimate rather than advice."],
  loan: ["The estimate assumes equal monthly repayments at the annual rate entered.", "It excludes fees, changes in rate and other lender terms.", "Use it for planning only and check current terms directly with a lender."],
  roi: ["ROI is net return divided by investment, expressed as a percentage.", "The calculation does not account for timing, tax or unrecorded costs.", "Use it as one part of a wider decision."],
  commission: ["Commission is sales amount multiplied by the percentage rate entered.", "It does not account for tiers, caps, refunds or deductions.", "Use it as an indicative starting point."],
};

export const calculatorKeywordTools: CalculatorDefinition[] = [
  { slug: "vat-calculator", kind: "vat", title: "VAT Calculator", detail: "Add or remove a chosen VAT rate.", path: "/tools/vat-calculator/", description: "Add tax to a net amount or remove it from a gross amount using the rate you enter.", assumptions: assumptions.vat },
  { slug: "sales-tax-calculator", kind: "sales-tax", title: "Sales Tax Calculator", detail: "Add or remove a chosen sales tax rate.", path: "/tools/sales-tax-calculator/", description: "Add sales tax to a net amount or remove it from a gross amount using the rate you enter.", assumptions: assumptions.vat },
  { slug: "profit-margin-calculator", kind: "margin", title: "Profit Margin Calculator", detail: "Calculate profit and margin from revenue and cost.", path: "/tools/profit-margin-calculator/", description: "Calculate profit and margin as a percentage of the revenue you enter.", assumptions: assumptions.margin },
  { slug: "gross-profit-margin-calculator", kind: "margin", title: "Gross Profit Margin Calculator", detail: "Calculate gross profit and margin from revenue and cost.", path: "/tools/gross-profit-margin-calculator/", description: "Calculate gross profit and margin as a percentage of the revenue you enter.", assumptions: assumptions.margin },
  { slug: "break-even-calculator", kind: "break-even", title: "Break-Even Calculator", detail: "Estimate units and revenue needed to cover costs.", path: "/tools/break-even-calculator/", description: "Estimate how many units you need to sell to cover fixed costs at a specified contribution per unit.", assumptions: assumptions.breakEven },
  { slug: "break-even-point-calculator", kind: "break-even", title: "Break-Even Point Calculator", detail: "Estimate the point where revenue covers costs.", path: "/tools/break-even-point-calculator/", description: "Estimate the sales units and revenue needed to cover fixed costs at a specified contribution per unit.", assumptions: assumptions.breakEven },
  { slug: "freelance-rate-calculator", kind: "freelance", title: "Freelance Rate Calculator", detail: "Calculate an indicative daily and hourly rate.", path: "/tools/freelance-rate-calculator/", description: "Estimate a starting daily and hourly rate from desired income, business expenses and available time.", assumptions: assumptions.freelance },
  { slug: "hourly-rate-calculator", kind: "freelance", title: "Hourly Rate Calculator", detail: "Calculate an indicative hourly rate from income and time.", path: "/tools/hourly-rate-calculator/", description: "Estimate a starting hourly rate from desired income, business expenses and available time.", assumptions: assumptions.freelance },
  { slug: "salary-calculator", kind: "salary", title: "Salary Calculator", detail: "Estimate monthly, weekly and hourly gross pay.", path: "/tools/salary-calculator/", description: "Estimate monthly, weekly and hourly gross pay from an annual salary and working time.", assumptions: assumptions.salary },
  { slug: "take-home-pay-calculator", kind: "take-home", title: "Take Home Pay Calculator", detail: "Estimate take-home pay using a deduction rate.", path: "/tools/take-home-pay-calculator/", description: "Estimate annual and monthly take-home pay from gross income and a deduction rate you enter.", assumptions: assumptions.takeHome },
  { slug: "business-loan-calculator", kind: "loan", title: "Business Loan Calculator", detail: "Estimate monthly loan repayments from amount, rate and term.", path: "/tools/business-loan-calculator/", description: "Estimate monthly repayments and total repayment from a loan amount, annual rate and term.", assumptions: assumptions.loan },
  { slug: "roi-calculator", kind: "roi", title: "ROI Calculator", detail: "Calculate return on investment from cost and return.", path: "/tools/roi-calculator/", description: "Calculate indicative net return and ROI from the investment and return you enter.", assumptions: assumptions.roi },
  { slug: "commission-calculator", kind: "commission", title: "Commission Calculator", detail: "Calculate commission from sales and a percentage rate.", path: "/tools/commission-calculator/", description: "Calculate indicative commission from the sales amount and percentage rate you enter.", assumptions: assumptions.commission },
];
