import { businessSoftwareKeywordPages } from "@/lib/business-software-pages";
import { crmKeywordPages } from "@/lib/crm-pages";
import { highIntentKeywordPages } from "@/lib/high-intent-keyword-pages";
import { longTailKeywordPages } from "@/lib/longtail-keyword-pages";
import { operationsGrowthPages } from "@/lib/operations-growth-pages";
import { seoKeywordPages } from "@/lib/seo-keyword-pages";
import { smallBusinessPillarPages } from "@/lib/small-business-pillar-pages";
import { specialistSoftwarePages } from "@/lib/specialist-software-pages";
import { strategicTechnologyPages } from "@/lib/strategic-technology-pages";

export type KeywordLandingPage = {
  slug: string;
  title: string;
  keyword: string;
  cluster?: string;
  path: string;
  hubPath: string;
  hubLabel: string;
  eyebrow: string;
  description: string;
  lead: string;
  decision: string;
  signals: { label: string; value: string }[];
  checkpoints: { title: string; detail: string }[];
  related: { title: string; path: string }[];
  reviewShortlist?: { name: string; review: string; comparison: string }[];
  reviewLens?: string;
};

const softwareRelated = [{ title: "Business software", path: "/business-software/" }, { title: "Software comparisons", path: "/comparisons/" }, { title: "Technology planning guide", path: "/business-guides/planning/" }];
const toolsRelated = [{ title: "Business tools", path: "/business-tools/" }, { title: "Free tools", path: "/free-tools/" }, { title: "Digital productivity guide", path: "/business-guides/productivity/" }];
const aiRelated = [{ title: "AI tools", path: "/ai-tools/" }, { title: "Business automation tools", path: "/business-automation-tools/" }, { title: "Everyday cybersecurity guide", path: "/business-guides/cybersecurity/" }];

export const keywordLandingPages: KeywordLandingPage[] = [
  ...businessSoftwareKeywordPages,
  ...crmKeywordPages,
  ...seoKeywordPages,
  ...longTailKeywordPages,
  ...operationsGrowthPages,
  ...specialistSoftwarePages,
  ...highIntentKeywordPages,
  ...strategicTechnologyPages,
  ...smallBusinessPillarPages,
  { slug: "small-business-software", title: "Small Business Software", keyword: "small business software", path: "/small-business-software/", hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Software category / focused fit", description: "Explore small business software by starting with the routine, people and information a new system must support.", lead: "Small business software is most useful when it removes a clear friction point without creating a heavier process to manage. Begin with the routine that needs attention, then narrow the category around the work and people involved.", decision: "What repeated job needs a clearer, more reliable way of working?", signals: [{ label: "JOB", value: "Name the routine" }, { label: "FIT", value: "Check the workflow" }, { label: "TEST", value: "Try the real work" }], checkpoints: [{ title: "Start with a recurring task", detail: "Choose work that happens often enough for an improvement to matter." }, { title: "Map the people and hand-offs", detail: "Check who starts, reviews and completes the process." }, { title: "Test the complete workflow", detail: "Use a real task rather than a feature list to assess fit." }], related: softwareRelated },
  { slug: "business-tools", title: "Business Tools", keyword: "business tools", path: "/business-tools/", hubPath: "/free-tools/", hubLabel: "Free Tools", eyebrow: "Tools category / practical work", description: "Explore business tools through the jobs they help clarify, calculate, coordinate and improve.", lead: "A business tool should create a clearer next action, not simply add another place to work. Use a defined task to decide whether a calculator, system or workflow aid is useful for your team.", decision: "Which decision or routine would benefit from a more visible starting point?", signals: [{ label: "TASK", value: "Choose the job" }, { label: "INPUT", value: "Use real context" }, { label: "MOVE", value: "Act on the result" }], checkpoints: [{ title: "Keep the task bounded", detail: "Start with one decision, process or calculation at a time." }, { title: "Use your own information", detail: "A result is only helpful when the starting assumptions reflect your work." }, { title: "Define the next action", detail: "Decide what the output should help you check, compare or improve." }], related: toolsRelated },
  { slug: "digital-tools", title: "Digital Tools", keyword: "digital tools", path: "/digital-tools/", hubPath: "/free-tools/", hubLabel: "Free Tools", eyebrow: "Tools category / everyday systems", description: "Use digital tools to support everyday work with clearer routines, useful information and visible decisions.", lead: "Digital tools work best when they fit the way people already coordinate, record information and follow through. Choose the task first, then assess the tool around the workflow it needs to support.", decision: "Where could a digital tool make an existing routine easier to complete well?", signals: [{ label: "WORK", value: "Observe the routine" }, { label: "ROLE", value: "Make ownership clear" }, { label: "REVIEW", value: "Keep what helps" }], checkpoints: [{ title: "See the current process", detail: "Notice where work waits, repeats or becomes difficult to find." }, { title: "Protect useful judgement", detail: "Use tools to reduce friction, not to hide important decisions." }, { title: "Review after use", detail: "Check whether the new approach is genuinely making the work clearer." }], related: toolsRelated },
  { slug: "online-business-tools", title: "Online Business Tools", keyword: "online business tools", path: "/online-business-tools/", hubPath: "/free-tools/", hubLabel: "Free Tools", eyebrow: "Tools category / connected work", description: "Explore online business tools through the practical work they support across people, systems and customer interactions.", lead: "Online business tools can make work more accessible and connected, but only when the information, permissions and hand-offs around them are deliberate. Assess the full routine, not only the interface.", decision: "What needs to stay clear when work moves between people and online systems?", signals: [{ label: "ACCESS", value: "Set the right roles" }, { label: "FLOW", value: "Follow the hand-offs" }, { label: "CHECK", value: "Keep oversight" }], checkpoints: [{ title: "Clarify access", detail: "Make ownership and permissions appropriate to the work involved." }, { title: "Follow information", detail: "Check how a request, record or update moves through the whole process." }, { title: "Keep a review point", detail: "Ensure people can spot exceptions and make the next judgement." }], related: toolsRelated },
  { slug: "free-business-tools", title: "Free Business Tools", keyword: "free business tools", path: "/free-business-tools/", hubPath: "/free-tools/", hubLabel: "Free Tools", eyebrow: "Tools category / useful starting points", description: "Find free business tools that provide a practical starting point for planning, calculations and everyday decisions.", lead: "Free business tools can be useful when their purpose and limits are clear. Start with an immediate task, use realistic inputs and treat the result as evidence for the next conversation rather than a final answer.", decision: "Which small calculation or planning task could benefit from a visible first pass?", signals: [{ label: "USE", value: "Choose one task" }, { label: "CHECK", value: "Read the assumptions" }, { label: "NEXT", value: "Use the output" }], checkpoints: [{ title: "Choose the right starting point", detail: "Use a tool that matches the question you are actually trying to answer." }, { title: "Make assumptions visible", detail: "Check the figures, scope and limits before relying on an output." }, { title: "Carry the insight forward", detail: "Turn the result into a useful next question or decision." }], related: toolsRelated },
  { slug: "ai-tools-for-small-business", title: "AI Tools for Small Business", keyword: "AI tools for small business", path: "/ai-tools-for-small-business/", hubPath: "/ai-tools/", hubLabel: "AI Tools", eyebrow: "AI category / bounded tasks", description: "Explore AI tools for small business by identifying a narrow task, maintaining review and protecting the information involved.", lead: "AI tools can support a small business when they help with a defined, repeatable part of the work and keep a person responsible for the final decision. Begin with a bounded task and clear review point.", decision: "Which repeated task could be improved while keeping human judgement in view?", signals: [{ label: "TASK", value: "Keep it narrow" }, { label: "REVIEW", value: "Retain ownership" }, { label: "DATA", value: "Check what is shared" }], checkpoints: [{ title: "Choose a repeatable starting task", detail: "Start with a draft, summary or preparation step rather than an open-ended process." }, { title: "Set a review standard", detail: "Define who checks the output before it is used externally or operationally." }, { title: "Consider information handling", detail: "Know what information is appropriate to place into the chosen service." }], related: aiRelated },
  { slug: "business-automation-tools", title: "Business Automation Tools", keyword: "business automation tools", path: "/business-automation-tools/", hubPath: "/ai-tools/", hubLabel: "AI Tools", eyebrow: "Automation category / visible routines", description: "Explore business automation tools by identifying predictable steps, clear ownership and sensible review points.", lead: "Business automation works best when it removes predictable administrative effort without obscuring the decision or exception that needs a person. Map the routine before connecting steps.", decision: "Which predictable step could be simplified without hiding a meaningful judgement?", signals: [{ label: "MAP", value: "Trace the routine" }, { label: "AUTOMATE", value: "Start with repetition" }, { label: "OWN", value: "Review exceptions" }], checkpoints: [{ title: "Map the hand-offs", detail: "Document where information starts, moves and needs a decision." }, { title: "Automate the predictable part", detail: "Begin with reminders, status changes or repeatable data movement." }, { title: "Keep an accountable owner", detail: "Make it obvious who checks exceptions and changes the routine." }], related: aiRelated },
  { slug: "productivity-tools", title: "Productivity Tools", keyword: "productivity tools", path: "/productivity-tools/", hubPath: "/ai-tools/", hubLabel: "AI Tools", eyebrow: "Productivity category / lighter work", description: "Explore productivity tools through the routines that create friction, repeated effort or lost context.", lead: "Productivity tools are useful when they make shared work easier to find, complete and review. Focus on the routine creating the most avoidable effort before adding another system.", decision: "Where does work repeatedly wait, duplicate effort or lose context?", signals: [{ label: "FIND", value: "Observe the drag" }, { label: "SIMPLIFY", value: "Create a default" }, { label: "REVIEW", value: "Keep it useful" }], checkpoints: [{ title: "Trace one routine", detail: "Follow a recurring task from the first request to the completed outcome." }, { title: "Create a shared default", detail: "Use a light, visible way to record the work, owner and next action." }, { title: "Remove what no longer helps", detail: "Review the process after a few cycles and simplify it again." }], related: toolsRelated },
  { slug: "accounting-software", title: "Accounting Software", keyword: "accounting software", path: "/accounting-software/", hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Software category / finance workflows", description: "Explore accounting software by mapping the finance routines, records and checks a business needs to manage.", lead: "Accounting software should be assessed through the routine you actually run: records, invoicing, expenses, reporting, collaboration and related checks. Confirm the current service details directly before changing a finance workflow.", decision: "Which finance routine needs to become clearer and more reliable for the people involved?", signals: [{ label: "ROUTINE", value: "List essential work" }, { label: "RECORDS", value: "Check the information" }, { label: "TRIAL", value: "Test with examples" }], checkpoints: [{ title: "List required finance tasks", detail: "Identify the recurring tasks that need to work from day one." }, { title: "Check connected workflows", detail: "Consider bank activity, billing, reporting, advisers and user access." }, { title: "Test realistic records", detail: "Use an appropriate trial or demonstration to validate the workflow." }], related: softwareRelated },
  { slug: "crm-software", title: "CRM Software", keyword: "CRM software", path: "/crm-software/", hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Software category / customer context", description: "Explore CRM software by focusing on the customer information, follow-up and relationship routines it must support.", lead: "CRM software is useful when it helps people see the right customer context, take the next action and maintain consistent follow-up. Map the relationship workflow before comparing features.", decision: "What customer context or follow-up routine needs to be more visible?", signals: [{ label: "CONTEXT", value: "See the relationship" }, { label: "FOLLOW-UP", value: "Make the next action clear" }, { label: "ADOPT", value: "Keep it usable" }], checkpoints: [{ title: "Map the customer journey", detail: "Identify where enquiries, conversations and decisions currently live." }, { title: "Clarify the next action", detail: "Check how ownership, follow-up and status are made visible." }, { title: "Keep records workable", detail: "Use a realistic contact or pipeline example to test everyday use." }], related: softwareRelated },
  { slug: "invoicing-software", title: "Invoicing Software", keyword: "invoicing software", path: "/invoicing-software/", hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Software category / billing routines", description: "Explore invoicing software around the billing, payment follow-up and record-keeping routines your business needs.", lead: "Invoicing software should make a billing routine clearer from the first invoice to payment follow-up and record keeping. Assess the workflow around approvals, customer communication and hand-offs.", decision: "Where could the billing and follow-up process become more consistent?", signals: [{ label: "ISSUE", value: "Create the invoice" }, { label: "FOLLOW", value: "Track the payment" }, { label: "RECORD", value: "Keep the context" }], checkpoints: [{ title: "Trace the billing path", detail: "Map the information needed to prepare, send and follow up an invoice." }, { title: "Check customer communication", detail: "Consider the clarity and timing of the messages around payment." }, { title: "Connect records deliberately", detail: "Assess how invoice information fits the wider finance routine." }], related: softwareRelated },
  { slug: "payroll-software", title: "Payroll Software", keyword: "payroll software", path: "/payroll-software/", hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Software category / pay routines", description: "Explore payroll software around the people, records, approvals and current requirements that shape a pay routine.", lead: "Payroll software needs careful evaluation because it sits alongside routine pay administration, employee information and changing requirements. Use the work your organisation carries to guide provider conversations and appropriate checks.", decision: "What does the payroll process need to make clear, consistent and reviewable?", signals: [{ label: "PEOPLE", value: "Map the roles" }, { label: "RECORDS", value: "Check the inputs" }, { label: "VERIFY", value: "Confirm the fit" }], checkpoints: [{ title: "Map the regular process", detail: "List the people, timings, approvals and records involved in a typical pay cycle." }, { title: "Identify essential checks", detail: "Define the controls and review steps that must remain visible." }, { title: "Confirm current suitability", detail: "Check service scope and relevant requirements directly before implementing a change." }], related: softwareRelated },
  { slug: "project-management-software", title: "Project Management Software", keyword: "project management software", path: "/project-management-software/", hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Software category / delivery visibility", description: "Explore project management software by following how work is planned, owned, updated and completed.", lead: "Project management software should make responsibilities, work status and delivery risks easier to see. Start with an active project and test how the system supports the real hand-offs around it.", decision: "Which part of planning or delivery is currently difficult for the team to see?", signals: [{ label: "PLAN", value: "Map the work" }, { label: "OWN", value: "Make responsibility visible" }, { label: "DELIVER", value: "Review the flow" }], checkpoints: [{ title: "Use a real project", detail: "Test with active work, dependencies and team roles rather than a blank board." }, { title: "Check responsibility", detail: "Make ownership, due dates and decisions easy to find." }, { title: "Review the delivery path", detail: "Follow how tasks move from request to completion and later learning." }], related: softwareRelated },
  { slug: "email-marketing-software", title: "Email Marketing Software", keyword: "email marketing software", path: "/email-marketing-software/", hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Software category / audience communication", description: "Explore email marketing software through the audience information, message workflow and follow-up needs it should support.", lead: "Email marketing software should help a business organise useful audience communication without losing clarity around lists, messages and next actions. Define the communication path before comparing tools.", decision: "What audience communication needs a clearer, more deliberate workflow?", signals: [{ label: "AUDIENCE", value: "Know the context" }, { label: "MESSAGE", value: "Make it useful" }, { label: "LEARN", value: "Review the path" }], checkpoints: [{ title: "Clarify the audience", detail: "Identify the relevant message, relationship and consent context before building a campaign." }, { title: "Plan the message path", detail: "Connect the subject, content and next action around one useful outcome." }, { title: "Review what people need", detail: "Use questions and responses to improve the clarity of future communication." }], related: softwareRelated },
  { slug: "booking-software", title: "Booking Software", keyword: "booking software", path: "/booking-software/", hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Software category / appointments", description: "Explore booking software around availability, appointment information, reminders and the customer experience.", lead: "Booking software should make it easier for customers and teams to understand availability, prepare for an appointment and follow through afterwards. Review the full journey from selection to confirmation.", decision: "Where could the appointment journey become clearer for customers and staff?", signals: [{ label: "AVAILABILITY", value: "Set the options" }, { label: "CONFIRM", value: "Keep details clear" }, { label: "FOLLOW", value: "Close the loop" }], checkpoints: [{ title: "Map the booking journey", detail: "Follow the customer path from choosing a time to attending or changing an appointment." }, { title: "Check the operational view", detail: "Ensure staff can see the information and next action they need." }, { title: "Review reminders and changes", detail: "Consider how confirmations, updates and follow-up work are handled." }], related: softwareRelated },
  { slug: "website-builders", title: "Website Builders", keyword: "website builders", path: "/website-builders/", hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Software category / web presence", description: "Explore website builders by starting with the pages, customer questions and ongoing work your business website needs to support.", lead: "Website builders should be assessed around the website’s practical job: helping people understand an offer, find relevant information and take a meaningful next step. Consider the ongoing content and ownership work as well as the first build.", decision: "What must a visitor be able to understand or do on your business website?", signals: [{ label: "AUDIENCE", value: "Name the question" }, { label: "CONTENT", value: "Plan the core pages" }, { label: "OWNERSHIP", value: "Keep it current" }], checkpoints: [{ title: "Start with the visitor task", detail: "Identify the information or action that matters most to the people you want to help." }, { title: "Plan the essential pages", detail: "Create a focused structure before evaluating templates or visual features." }, { title: "Consider ongoing ownership", detail: "Check how content, access, updates and support will be managed over time." }], related: softwareRelated },
];

export const keywordLandingBySlug = Object.fromEntries(keywordLandingPages.map((page) => [page.slug, page])) as Record<string, KeywordLandingPage>;
