type Cluster = "accounting" | "invoicing" | "ai" | "productivity" | "marketing" | "free-tools" | "comparisons";
type Entry = [slug: string, title: string, keyword: string];

const definitions: Record<Cluster, { hubPath: string; hubLabel: string; eyebrow: string; description: (keyword: string) => string; lead: (keyword: string) => string; decision: string; signals: { label: string; value: string }[]; checkpoints: { title: string; detail: string }[] }> = {
  accounting: { hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Accounting category / reliable records", description: (keyword) => `Explore ${keyword} by mapping the finance records, reporting, collaboration and review routines a business needs to keep clear.`, lead: (keyword) => `${keyword} is most useful when it supports the finance routine people actually run: keeping records current, checking information and creating a more reliable view of the business.`, decision: "Which finance routine needs clearer records, stronger visibility and a more dependable review point?", signals: [{ label: "RECORD", value: "Keep inputs clear" }, { label: "REVIEW", value: "Check the routine" }, { label: "DECIDE", value: "Use the evidence" }], checkpoints: [{ title: "Map the recurring finance work", detail: "Identify the records, people and review steps that matter most." }, { title: "Test realistic information", detail: "Use an appropriate example of the work rather than a feature list." }, { title: "Confirm the current fit", detail: "Check provider details and workflow scope before making a change." }] },
  invoicing: { hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Invoicing category / clear payment paths", description: (keyword) => `Explore ${keyword} around the billing, payment follow-up and record-keeping work your business needs to make consistent.`, lead: (keyword) => `${keyword} should make it easier to create a clear billing path, retain the relevant context and follow up at the right point in the routine.`, decision: "Where could billing, payment follow-up or invoice information become more consistent for your team and customers?", signals: [{ label: "ISSUE", value: "Prepare the invoice" }, { label: "FOLLOW", value: "Keep the next action clear" }, { label: "RECORD", value: "Retain the context" }], checkpoints: [{ title: "Trace the billing path", detail: "Follow the work from the original request through to payment follow-up." }, { title: "Check customer clarity", detail: "Make the amount, timing and next action understandable." }, { title: "Review connected records", detail: "Check how invoices fit the wider finance routine." }] },
  ai: { hubPath: "/ai-tools/", hubLabel: "AI Tools", eyebrow: "AI category / bounded useful work", description: (keyword) => `Explore ${keyword} by identifying a bounded task, an appropriate review point and the information the workflow needs to handle carefully.`, lead: (keyword) => `${keyword} can be useful when it assists with a clear part of the work while a person remains responsible for the outcome and the information involved.`, decision: "Which bounded task could benefit from AI assistance while keeping ownership, review and context visible?", signals: [{ label: "TASK", value: "Set the useful boundary" }, { label: "REVIEW", value: "Keep judgement visible" }, { label: "DATA", value: "Check the information" }], checkpoints: [{ title: "Choose one repeatable task", detail: "Begin with a defined draft, preparation or support step." }, { title: "Set a review standard", detail: "Make clear who checks the output before it is used." }, { title: "Consider information handling", detail: "Know what should and should not enter the workflow." }] },
  productivity: { hubPath: "/ai-tools/", hubLabel: "AI Tools", eyebrow: "Productivity category / lighter routines", description: (keyword) => `Explore ${keyword} by focusing on repeated friction, clearer ownership and the shared routines that help work move forward.`, lead: (keyword) => `${keyword} should reduce avoidable effort from everyday work and make the next action easier to find, complete and review.`, decision: "Which repeated routine would benefit from less friction and a clearer next action?", signals: [{ label: "FIND", value: "Observe the friction" }, { label: "SIMPLIFY", value: "Set a useful default" }, { label: "REVIEW", value: "Keep what helps" }], checkpoints: [{ title: "Follow one routine", detail: "Trace a task from first request to finished outcome." }, { title: "Make ownership visible", detail: "Keep the current owner, context and next action easy to find." }, { title: "Review the change", detail: "Retain only the steps that genuinely reduce effort." }] },
  marketing: { hubPath: "/business-software/", hubLabel: "Business Software", eyebrow: "Marketing category / useful audience signals", description: (keyword) => `Explore ${keyword} by connecting audience context, useful messages and a clear path to the next customer action.`, lead: (keyword) => `${keyword} is most useful when it helps a team organise a clear message, understand audience response and improve the path from attention to action.`, decision: "What audience question, message or next action needs a clearer marketing workflow?", signals: [{ label: "AUDIENCE", value: "Know the context" }, { label: "MESSAGE", value: "Make it useful" }, { label: "LEARN", value: "Improve the path" }], checkpoints: [{ title: "Clarify the audience need", detail: "Start with the situation or question the work should address." }, { title: "Map the message path", detail: "Connect the content, channel and next action deliberately." }, { title: "Review the response", detail: "Use questions and outcomes to improve the next iteration." }] },
  "free-tools": { hubPath: "/free-tools/", hubLabel: "Free Tools", eyebrow: "Free tools category / practical starting points", description: (keyword) => `Explore ${keyword} by choosing a defined business task, making assumptions visible and using the result as a practical next step.`, lead: (keyword) => `${keyword} can be useful when its purpose and limits are clear. Start with one question, use realistic inputs and treat the output as evidence for the next decision.`, decision: "Which immediate business question could benefit from a clear first pass and visible assumptions?", signals: [{ label: "QUESTION", value: "Choose the job" }, { label: "INPUT", value: "Use real context" }, { label: "NEXT", value: "Act on the result" }], checkpoints: [{ title: "Bound the task", detail: "Use one calculator or tool around one practical question." }, { title: "Make assumptions visible", detail: "Check the inputs, scope and limits before relying on an output." }, { title: "Carry the insight forward", detail: "Turn the result into the next useful action or conversation." }] },
  comparisons: { hubPath: "/comparisons/", hubLabel: "Software Comparisons", eyebrow: "Comparison category / same workflow", description: (keyword) => `Use this ${keyword} framework to compare options around the same business job, workflow, ownership and implementation effort.`, lead: (keyword) => `A ${keyword} is most useful when every option is tested against the same real work rather than compared through a generic feature list.`, decision: "Which real workflow should every option be able to support before you compare products or plans?", signals: [{ label: "SAME JOB", value: "Set the comparison task" }, { label: "SAME TEST", value: "Use shared evidence" }, { label: "SAME CHECK", value: "Review adoption work" }], checkpoints: [{ title: "Define shared criteria", detail: "Use the same business task and evidence for every option." }, { title: "Test the same scenario", detail: "Compare the workflow using a realistic example of the work." }, { title: "Check the implementation", detail: "Consider ownership, data, adoption and provider detail before deciding." }] },
};

function pages(cluster: Cluster, entries: Entry[]) {
  const definition = definitions[cluster];
  return entries.map(([slug, title, keyword]) => ({ slug, title, keyword, cluster, path: `/${slug}/`, hubPath: definition.hubPath, hubLabel: definition.hubLabel, eyebrow: definition.eyebrow, description: definition.description(keyword), lead: definition.lead(keyword), decision: definition.decision, signals: definition.signals, checkpoints: definition.checkpoints, related: [] }));
}

export const seoKeywordPages = [
  ...pages("accounting", [["accounting-software-for-small-business", "Accounting Software for Small Business", "accounting software for small business"], ["best-accounting-software", "Best Accounting Software", "best accounting software"], ["free-accounting-software", "Free Accounting Software", "free accounting software"], ["accounting-software-for-freelancers", "Accounting Software for Freelancers", "accounting software for freelancers"], ["accounting-software-for-startups", "Accounting Software for Startups", "accounting software for startups"], ["online-accounting-software", "Online Accounting Software", "online accounting software"], ["small-business-accounting-tools", "Small Business Accounting Tools", "small business accounting tools"]]),
  ...pages("invoicing", [["invoice-software", "Invoice Software", "invoice software"], ["free-invoice-software", "Free Invoice Software", "free invoice software"], ["invoice-generator", "Invoice Generator", "invoice generator"], ["free-invoice-generator", "Free Invoice Generator", "free invoice generator"], ["online-invoice-generator", "Online Invoice Generator", "online invoice generator"], ["recurring-invoice-software", "Recurring Invoice Software", "recurring invoice software"]]),
  ...pages("ai", [["best-ai-tools", "Best AI Tools", "best AI tools"], ["ai-tools-for-business", "AI Tools for Business", "AI tools for business"], ["ai-productivity-tools", "AI Productivity Tools", "AI productivity tools"], ["ai-automation-tools", "AI Automation Tools", "AI automation tools"], ["ai-marketing-tools", "AI Marketing Tools", "AI marketing tools"], ["ai-writing-tools", "AI Writing Tools", "AI writing tools"], ["ai-business-tools", "AI Business Tools", "AI business tools"], ["free-ai-tools", "Free AI Tools", "free AI tools"], ["ai-tools-for-entrepreneurs", "AI Tools for Entrepreneurs", "AI tools for entrepreneurs"], ["ai-tools-for-freelancers", "AI Tools for Freelancers", "AI tools for freelancers"]]),
  ...pages("productivity", [["productivity-apps", "Productivity Apps", "productivity apps"], ["best-productivity-tools", "Best Productivity Tools", "best productivity tools"], ["productivity-tools-for-business", "Productivity Tools for Business", "productivity tools for business"], ["productivity-tools-for-small-business", "Productivity Tools for Small Business", "productivity tools for small business"], ["time-management-tools", "Time Management Tools", "time management tools"]]),
  ...pages("marketing", [["digital-marketing-tools", "Digital Marketing Tools", "digital marketing tools"], ["best-digital-marketing-tools", "Best Digital Marketing Tools", "best digital marketing tools"], ["email-marketing-tools", "Email Marketing Tools", "email marketing tools"], ["social-media-management-tools", "Social Media Management Tools", "social media management tools"], ["seo-tools-for-small-business", "SEO Tools for Small Business", "SEO tools for small business"], ["content-marketing-tools", "Content Marketing Tools", "content marketing tools"]]),
  ...pages("free-tools", [["free-online-tools", "Free Online Tools", "free online tools"], ["business-calculator", "Business Calculator", "business calculator"], ["online-calculator-for-business", "Online Calculator for Business", "online calculator for business"], ["small-business-tools", "Small Business Tools", "small business tools"], ["tools-for-entrepreneurs", "Tools for Entrepreneurs", "tools for entrepreneurs"]]),
  ...pages("comparisons", [["software-comparison", "Software Comparison", "software comparison"], ["business-software-comparison", "Business Software Comparison", "business software comparison"], ["crm-comparison", "CRM Comparison", "CRM comparison"], ["accounting-software-comparison", "Accounting Software Comparison", "accounting software comparison"], ["project-management-software-comparison", "Project Management Software Comparison", "project management software comparison"], ["email-marketing-software-comparison", "Email Marketing Software Comparison", "email marketing software comparison"]]),
];
