export type AuthorityPillar = {
  slug: string;
  index: string;
  title: string;
  eyebrow: string;
  summary: string;
  hubPath: string;
  clusters: string[];
  featuredSlugs: string[];
};

export const clusterTopicLabels: Record<string, string> = {
  accounting: "Accounting & finance", ai: "AI tools", "ai-automation": "AI & automation", "ai-business-use-cases": "AI use cases", "analytics-reporting": "Analytics & reporting", "business-software": "Business software", calculators: "Business calculators", "communication-utilities": "Communication utilities", comparisons: "Software comparisons", "customer-management": "Customer management", "data-spreadsheets": "Data & spreadsheets", "documents-productivity": "Documents & productivity", "ecommerce-systems": "E-commerce systems", "file-media-utilities": "File & media utilities", "finance-invoicing": "Finance & invoicing", "free-tools": "Free business tools", "freelancer-work": "Freelancer work", "high-intent-evaluation": "High-intent evaluations", "how-to": "How-to guides", "interactive-tool-opportunities": "Interactive tool opportunities", "inventory-operations": "Inventory & operations", invoicing: "Invoicing & payments", "knowledge-systems": "Knowledge systems", "legacy-general": "Business software foundations", "legal-compliance": "Legal & compliance", marketing: "Marketing", "marketing-web": "Marketing & web", "no-code-developer": "No-code & developer tools", "operations-analytics": "Operations & analytics", "payments-billing": "Payments & billing", "people-operations": "People operations", productivity: "Productivity", "productivity-collaboration": "Productivity & collaboration", "recruitment-hiring": "Recruitment & hiring", "remote-work": "Remote work", "sales-customer": "Sales & customer operations", "sales-revenue": "Lead generation & sales", "scheduling-appointments": "Scheduling & appointments", "security-storage": "Security & storage", "seo-tools": "SEO tools", "small-business-guides": "Small-business guides", "small-business-practical": "Small-business practical guides", "startup-operations": "Startup operations", utilities: "Generators & utilities", "website-tools": "Website tools"
};

Object.assign(clusterTopicLabels, {
  "business-technology": "Business technology", "digital-transformation": "Digital transformation", "business-process-improvement": "Business process improvement", "business-automation": "Business automation", "business-productivity": "Business productivity", "business-workflow": "Business workflow", "data-management": "Data management", "business-intelligence": "Business intelligence", "customer-experience": "Customer experience", "marketing-operations": "Marketing operations", "sales-operations": "Sales operations", "revenue-and-growth": "Revenue & growth", saas: "SaaS operations", "software-buying-research": "Software buying research", "integrations-and-apis": "Integrations & APIs", "cybersecurity-and-business-safety": "Business cybersecurity", "topical-authority-supporting-terms": "Software lifecycle guidance"
});

Object.assign(clusterTopicLabels, {
  "small-business-technology": "Small-business technology", "small-business-transformation": "Small-business transformation", "small-business-process": "Small-business process improvement", "small-business-automation": "Small-business automation", "small-business-productivity": "Small-business productivity", "small-business-workflow": "Small-business workflow", "small-business-data": "Small-business data management", "small-business-intelligence": "Small-business intelligence", "small-business-customer-experience": "Small-business customer experience", "small-business-marketing-operations": "Small-business marketing operations", "small-business-sales-operations": "Small-business sales operations", "small-business-growth": "Small-business growth", "small-business-saas": "Small-business SaaS", "small-business-software-buying": "Small-business software buying", "small-business-integrations": "Small-business integrations", "small-business-cybersecurity": "Small-business cybersecurity"
});

export const topicAuthorityPillars: AuthorityPillar[] = [
  { slug: "revenue-finance", index: "01", title: "Revenue & finance systems", eyebrow: "Pillar / money in, money out, records in view", summary: "Trace the path from an invoice, expense or payment decision to the record, approval and next financial action.", hubPath: "/business-software/", clusters: ["accounting", "invoicing", "finance-invoicing", "payments-billing", "revenue-and-growth", "small-business-growth"], featuredSlugs: ["accounting-software", "invoicing-software", "payment-processing-software", "cash-flow-forecasting-software"] },
  { slug: "customer-revenue", index: "02", title: "Customer & revenue operations", eyebrow: "Pillar / relationship to opportunity", summary: "Connect customer context, pipeline movement and follow-up so the team can see who owns the next useful action.", hubPath: "/business-software/", clusters: ["customer-management", "sales-customer", "sales-revenue", "customer-experience", "sales-operations", "small-business-customer-experience", "small-business-sales-operations"], featuredSlugs: ["crm-software", "customer-management-software", "lead-generation-tools", "sales-pipeline-tools"] },
  { slug: "business-operations", index: "03", title: "Business operations & delivery", eyebrow: "Pillar / routine to reliable result", summary: "Make the operating routine visible across planning, capacity, inventory, scheduling and the exceptions that need review.", hubPath: "/business-software/", clusters: ["business-software", "legacy-general", "operations-analytics", "inventory-operations", "scheduling-appointments", "freelancer-work", "startup-operations", "business-technology", "digital-transformation", "business-process-improvement", "small-business-technology", "small-business-transformation", "small-business-process"], featuredSlugs: ["business-software", "business-operations-software", "inventory-software", "appointment-scheduling-software"] },
  { slug: "analytics-reporting", index: "04", title: "Analytics & decision intelligence", eyebrow: "Pillar / source to useful operating signal", summary: "Define the metric, retain the source and make the reporting view useful for the team that needs to act on it.", hubPath: "/business-software/", clusters: ["analytics-reporting", "data-management", "business-intelligence", "small-business-data", "small-business-intelligence"], featuredSlugs: ["business-analytics-tools", "business-intelligence-software", "data-visualization-software", "kpi-dashboard"] },
  { slug: "growth-commerce", index: "05", title: "Growth, web & commerce", eyebrow: "Pillar / audience to customer journey", summary: "Follow the path from audience question and website signal to product information, order movement and useful customer follow-up.", hubPath: "/business-software/", clusters: ["marketing", "marketing-web", "website-tools", "seo-tools", "ecommerce-systems", "marketing-operations", "small-business-marketing-operations"], featuredSlugs: ["digital-marketing-tools", "website-builders", "ecommerce-tools", "keyword-research-tool"] },
  { slug: "ai-automation", index: "06", title: "AI, automation & no-code", eyebrow: "Pillar / bounded task to human review", summary: "Use AI and automation where the task, data, responsible person and exception path can remain explicit and reviewable.", hubPath: "/ai-tools/", clusters: ["ai", "ai-automation", "ai-business-use-cases", "no-code-developer", "business-automation", "business-workflow", "integrations-and-apis", "small-business-automation", "small-business-workflow", "small-business-integrations"], featuredSlugs: ["ai-tools", "ai-automation-tools", "ai-for-small-business", "no-code-tools"] },
  { slug: "team-knowledge", index: "07", title: "Team, knowledge & productivity", eyebrow: "Pillar / shared context to completed work", summary: "Help people find the source, coordinate the hand-off and retain the useful record around their everyday work.", hubPath: "/ai-tools/", clusters: ["productivity", "productivity-collaboration", "documents-productivity", "knowledge-systems", "remote-work", "data-spreadsheets", "business-productivity", "small-business-productivity"], featuredSlugs: ["productivity-tools", "document-automation-software", "knowledge-management-software", "remote-work-tools"] },
  { slug: "people-governance", index: "08", title: "People, governance & risk", eyebrow: "Pillar / people records to controlled evidence", summary: "Keep hiring, workforce, compliance, security and controlled records connected to the decisions people need to make.", hubPath: "/business-software/", clusters: ["people-operations", "recruitment-hiring", "legal-compliance", "security-storage", "cybersecurity-and-business-safety", "small-business-cybersecurity"], featuredSlugs: ["hr-software", "recruitment-management-software", "contract-management-system", "cybersecurity-tools"] },
  { slug: "practical-tools", index: "09", title: "Practical tools & utilities", eyebrow: "Pillar / useful input to reviewed output", summary: "Use calculators, generators and file utilities as transparent starting points for a bounded business question or working output.", hubPath: "/free-tools/", clusters: ["free-tools", "calculators", "utilities", "interactive-tool-opportunities", "file-media-utilities", "communication-utilities"], featuredSlugs: ["business-calculator", "roi-calculator", "invoice-number-generator", "pdf-editor-online"] },
  { slug: "practical-guides", index: "10", title: "Small-business practical guides", eyebrow: "Pillar / question to next useful step", summary: "Break recurring business problems into a manageable routine, an accountable owner and a review point that improves the next cycle.", hubPath: "/business-guides/", clusters: ["how-to", "small-business-guides", "small-business-practical"], featuredSlugs: ["how-to-choose-business-software", "how-to-manage-a-small-business", "how-to-invoice-a-client", "business-guides"] },
  { slug: "software-evaluation", index: "11", title: "Software reviews & evaluations", eyebrow: "Pillar / product scope to evidence-led fit", summary: "Read product information with a checklist, then compare options using the same practical workflow rather than a generic winner.", hubPath: "/comparisons/", clusters: ["comparisons", "high-intent-evaluation", "saas", "software-buying-research", "topical-authority-supporting-terms", "small-business-saas", "small-business-software-buying"], featuredSlugs: ["software-comparison", "business-software-comparison", "crm-comparison", "best-business-software"] }
];

const clusterToPillar = new Map(topicAuthorityPillars.flatMap((pillar) => pillar.clusters.map((cluster) => [cluster, pillar] as const)));

export function getAuthorityPillar(cluster?: string) {
  return cluster ? clusterToPillar.get(cluster) : undefined;
}
