/** Editorial Terminal: asymmetric publication-style homepage with interface specimens and decision-led content. */
import { ArrowDownRight, ArrowUpRight, CheckCircle2, ChevronRight, Sparkles, Calculator, LayoutDashboard, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import PageMeta from "@/components/PageMeta";
import { calculatorTools, hubs } from "@/lib/site-data";
import "@/components/home-aeo.css";

const heroImage = "/images/hero-editorial-terminal.webp";
const softwareImage = "/images/software-specimen.webp";
const toolsImage = "/images/tools-specimen.webp";

const homepageRoutes = [
  { title: "Business Software", description: "Compare CRM, accounting, project management, HR and the systems behind everyday business work.", path: "/business-software/" },
  { title: "Business Automation", description: "Map repeatable work, workflow automation and no-code connections with useful human review.", path: "/business-automation/" },
  { title: "AI Tools", description: "Explore practical AI business tools for productivity, marketing, research and carefully checked automation.", path: "/ai-tools/" },
  { title: "Business Tools", description: "Use calculators, generators and practical online tools to prepare a more informed business decision.", path: "/free-tools/" },
  { title: "Business Guides", description: "Read straightforward guidance on technology, productivity, digital marketing and cybersecurity.", path: "/business-guides/" },
  { title: "Software Comparisons", description: "Compare business software around the job, workflow, information and implementation effort that matter.", path: "/comparisons/" }
] as const;

const homeFaqs = [
  { question: "What is business software?", answer: "Business software is an application or connected set of applications that helps a business run a defined activity, such as accounting, customer relationship management, project delivery, payroll, marketing, reporting or communication." },
  { question: "How do I choose business software?", answer: "Start with the business task and the people, records, systems and decisions around it. Test a realistic workflow, verify the current plan and implementation requirements, then record the evidence before choosing." },
  { question: "What business software does a small business need?", answer: "The right starting point depends on the business model and current bottleneck. Many small businesses first evaluate accounting, invoicing, customer management, collaboration, website, marketing and security workflows rather than buying a large stack at once." },
  { question: "What is the difference between business software and business automation?", answer: "Business software gives teams a system for completing and recording work. Business automation connects defined steps or triggers so repeatable work can move with less manual effort, while keeping owners and exception reviews visible." },
  { question: "Should a business use AI tools with its software stack?", answer: "AI tools can support bounded tasks such as drafting, research preparation, summaries and routine assistance. Define the task, check privacy and quality requirements, and keep an appropriate person responsible for reviewing the result." }
] as const;

export default function Home() {
  return <div className="site-shell">
    <PageMeta title="Business Software, Tools & Automation Solutions" path="/" description="Discover business software, AI tools, automation solutions, productivity tools and practical digital resources to help businesses work smarter and grow." faqItems={homeFaqs} />
    <SiteHeader />
    <main id="main-content">
      <section className="hero-section">
        <div className="hero-copy">
          <div className="hero-eyebrow"><span className="pulse-dot" /> Business software for better work</div>
          <h1>Business Software, Tools & <em>Digital Solutions.</em></h1>
          <p>Discover business software, AI tools, automation solutions, productivity tools and practical digital resources to help businesses work smarter and grow.</p>
          <div className="hero-actions"><Link className="button button-primary" href="/business-software/">Browse business software <ArrowUpRight size={17} /></Link><Link className="button button-quiet" href="/business-automation/">Explore automation <ChevronRight size={17} /></Link></div>
          <div className="hero-proof"><span><CheckCircle2 size={16} />Business software, chosen with context</span><span><CheckCircle2 size={16} />No invented claims</span></div>
        </div>
        <div className="hero-art"><div className="hero-grid" /><div className="hero-terminal-axis"><span>01 / SOFTWARE SYSTEM</span><i /><b>BUSINESS CONTEXT</b></div><img src={heroImage} alt="Business software dashboard, workflow and decision interface illustration" fetchPriority="high" /><div className="hero-readout"><span>STACK / 01</span><b>WORKFLOW</b><i /><b>OWNER</b><i /><b>REVIEW</b></div><div className="hero-art-label"><span>01</span><p>Choose the work.<br />Then choose the tool.</p></div></div>
      </section>

      <section className="signal-strip" aria-label="What DigitalSolutions.cv offers"><div><span>01</span><p>Business software for the job</p></div><div><span>02</span><p>Automation with practical oversight</p></div><div><span>03</span><p>Digital solutions with context</p></div></section>

      <section className="home-bluf" aria-labelledby="business-software-answer"><div><span>DIRECT ANSWER / 01</span><p id="business-software-answer"><strong>Business software helps organisations run core work through connected tools for finance, customers, projects, people, communication and reporting. Choose it by the business task, the workflow it must improve, the information it touches and the review needed before a team relies on it.</strong></p><Link href="/business-software/">Browse the business software hub <ArrowUpRight size={16} /></Link></div><aside><span>RESEARCH SIGNAL / 2025</span><p>In a U.S. Chamber survey, 84% of small businesses said they planned to increase their use of technology platforms. Treat this as context—not a reason to add software without a clear job, owner and test plan.</p><a href="https://www.uschamber.com/technology/empowering-small-business-the-impact-of-technology-on-u-s-small-business" target="_blank" rel="noreferrer">Read the 2025 research source <ArrowUpRight size={15} /></a></aside></section>

      <section className="section category-section">
        <div className="section-head split-head"><div><span className="eyebrow">Explore the business software stack</span><h2>A clearer path from software to <em>better work.</em></h2></div><p>Start with the business outcome that needs improving. Each route brings together useful tools, practical guidance and the questions worth asking before the next decision.</p></div>
        <div className="category-grid">{homepageRoutes.map((route, index) => { const Icon = [LayoutDashboard, Sparkles, ShieldCheck, Calculator, CheckCircle2, ArrowDownRight][index]; return <Link href={route.path} className="category-card" key={route.title}><div className="category-card-top"><span>0{index + 1}</span><Icon size={21} /></div><h3>{route.title}</h3><p>{route.description}</p><span className="card-link">Explore <ArrowUpRight size={16} /></span></Link>; })}</div>
      </section>

      <section className="section feature-band software-band"><div className="feature-copy"><span className="eyebrow">Business software</span><h2>Find business software that fits <em>the work in front of you.</em></h2><p>Explore CRM, accounting, invoicing, payroll, project management and more. Use practical prompts to define the job, map the workflow, consider the technology stack and check what matters before you sign up.</p><Link className="text-link" href="/business-software/">Browse business software <ArrowUpRight size={17} /></Link></div><div className="feature-visual light-visual"><img src={softwareImage} alt="Abstract business software dashboard illustration" loading="lazy" /><div className="annotation-card"><span>WORKFLOW FIRST</span><p>Start with the business task that needs to improve.</p></div></div></section>

      <section className="section software-decision-canvas" aria-labelledby="software-decision-title"><div className="decision-canvas-intro"><span className="eyebrow">Business software decision canvas</span><h2 id="software-decision-title">Build a business software shortlist around structured evidence.</h2><p>A useful software choice connects four practical factors: the task that needs to change, the people who own it, the information that moves through it and the review point that makes a result safe to use. This canvas gives every option the same test.</p></div><div className="decision-canvas-graphic" role="img" aria-label="Business software decision canvas showing task, people, information and review connected as one workflow"><div><span>01 / TASK</span><b>What must improve?</b><p>Name the repeatable job in plain language.</p></div><i /><div><span>02 / PEOPLE</span><b>Who starts, owns and checks it?</b><p>Make the hand-offs and exceptions visible.</p></div><i /><div><span>03 / INFORMATION</span><b>Which records matter?</b><p>Identify the source, quality check and access need.</p></div><i /><div><span>04 / REVIEW</span><b>What proves the fit?</b><p>Test the same realistic workflow before deciding.</p></div></div><div className="decision-canvas-links"><Link href="/crm-software/">Compare CRM software <ArrowUpRight size={16} /></Link><Link href="/accounting-software/">Explore accounting software <ArrowUpRight size={16} /></Link><Link href="/project-management-software/">Assess project management software <ArrowUpRight size={16} /></Link></div></section>

      <section className="section software-explainer" aria-labelledby="business-software-explainer"><div className="software-explainer-rail"><span>BUSINESS SOFTWARE / 02</span><b>CORE<br />WORK</b><i /></div><div><span className="eyebrow">How business software supports work</span><h2 id="business-software-explainer">Business software is a system for work—not just a list of features.</h2><p>Business software can support a single activity, such as invoicing or appointment booking, or connect several parts of a workflow. The most useful starting point is not “Which platform is best?” It is “Which business outcome needs a clearer, faster or more reliable path?” That question produces better requirements and more useful product comparisons.</p><div className="software-entity-grid"><article><span>FINANCE &amp; ADMIN</span><h3>Keep records and routine work visible.</h3><p>Evaluate <Link href="/accounting-software/">accounting software</Link>, invoicing, payroll and expense workflows against the records, approvals and reporting the business actually needs.</p></article><article><span>CUSTOMERS &amp; GROWTH</span><h3>Make customer context usable.</h3><p>Use <Link href="/crm-software/">CRM software</Link>, marketing and customer-service tools to keep enquiries, follow-up, conversations and next actions connected.</p></article><article><span>DELIVERY &amp; OPERATIONS</span><h3>Coordinate the work between people.</h3><p>Check project, workflow and <Link href="/business-automation/">business automation</Link> tools against the hand-offs, ownership and exceptions that make delivery work.</p></article><article><span>INFORMATION &amp; DECISIONS</span><h3>Turn records into a usable next step.</h3><p>Assess reporting, dashboards, document and <Link href="/ai-tools/">AI tools for business</Link> around data quality, privacy, review and the decision they are meant to support.</p></article></div></div></section>

      <section className="section software-selection" aria-labelledby="software-selection-title"><div className="section-head split-head"><div><span className="eyebrow">Software selection method</span><h2 id="software-selection-title">How to choose business software without feature-list drift.</h2></div><p>Use the same four tests for every option. A direct product demonstration, realistic trial or provider conversation should add evidence to these questions—not replace them.</p></div><ol><li><span>01</span><div><h3>Define the business job.</h3><p>Write the task, outcome and practical constraint in one sentence. “Reduce time spent reconciling invoices” is more useful than “Find a better finance platform.”</p></div></li><li><span>02</span><div><h3>Map a real workflow.</h3><p>Follow one request, customer record, document or transaction from start to finish. Include the people, systems, approvals and exception routes around it.</p></div></li><li><span>03</span><div><h3>Test the same scenario.</h3><p>Compare options using the same realistic task. Confirm the current plan, implementation effort, data handling, integrations and user permissions that the scenario requires.</p></div></li><li><span>04</span><div><h3>Record the decision evidence.</h3><p>Keep a short record of what improved, what stayed difficult, who needs training and what should be reviewed after implementation. This prevents a feature list from becoming the decision.</p></div></li></ol></section>

      <section className="section ai-section"><div className="ai-head"><span className="eyebrow">AI tools</span><h2>Useful AI starts with <em>human judgement.</em></h2><Link className="button button-outline" href="/ai-tools/">Explore AI tools <ArrowUpRight size={16} /></Link></div><div className="ai-routes">{hubs["ai-tools"].items.map((item, index) => <Link href="/ai-tools/" key={item.title}><span>0{index + 1}</span><h3>{item.title}</h3><p>{item.detail}</p><ArrowUpRight size={18} /></Link>)}</div></section>

      <section className="section tools-section"><div className="tools-visual"><img src={toolsImage} alt="Abstract calculator and business tools illustration" loading="lazy" /><span className="tools-index">TOOLS / 04</span></div><div className="tools-copy"><span className="eyebrow">Free business tools</span><h2>Run the numbers <em>before you commit.</em></h2><p>Use working calculators to sense-check VAT, margins, break-even points and freelance rates. They work in your browser and explain their limits.</p><div className="tool-list">{calculatorTools.map((tool) => <Link href={tool.path} key={tool.slug}><span>{tool.title}</span><ArrowUpRight size={16} /></Link>)}</div><Link className="text-link" href="/free-tools/">See all free tools <ArrowUpRight size={17} /></Link></div></section>

      <section className="section editorial-section"><div className="section-head"><span className="eyebrow">Build the right digital foundation</span><h2>Keep the software research <em>grounded.</em></h2></div><div className="article-grid"><article><span className="article-type">Software guide</span><h3>How to choose business software for your work</h3><p>Translate a broad business software search into practical requirements, shared workflows and selection criteria.</p><Link href="/business-software/">Read the framework <ArrowUpRight size={16} /></Link></article><article className="article-dark"><span className="article-type">Automation guide</span><h3>Which business processes should be automated?</h3><p>Start with repeatable work, make the exception route visible, and retain human review where it matters.</p><Link href="/business-automation/">Explore automation <ArrowUpRight size={16} /></Link></article><article><span className="article-type">Comparison</span><h3>Compare business software by the job it needs to do</h3><p>Move beyond brand lists by focusing on workflow fit, responsibilities, technology context and verification.</p><Link href="/comparisons/">Compare with context <ArrowUpRight size={16} /></Link></article></div></section>

      <section className="section home-faq" aria-labelledby="business-software-faq"><div className="section-head split-head"><div><span className="eyebrow">Business software FAQs</span><h2 id="business-software-faq">Clear answers before the next software decision.</h2></div><p>These direct answers summarise the core decision framework. Use the related hubs to research the business category, then verify current product details with the provider.</p></div><div>{homeFaqs.map((item, index) => <article key={item.question}><span>0{index + 1}</span><h3>{item.question}</h3><p>{item.answer}</p></article>)}</div></section>

      <section className="contact-cta"><div><span className="eyebrow">Keep it practical</span><h2>Have a correction, a useful tool idea or a question?</h2></div><div><p>DigitalSolutions.cv is designed to improve through clear, specific feedback.</p><Link className="button button-primary" href="/contact/">Contact DigitalSolutions.cv <ArrowUpRight size={17} /></Link></div></section>
    </main>
    <SiteFooter />
  </div>;
}
