/** Editorial Terminal: reusable content hubs with an editorial route into practical categories. */
import { ArrowUpRight, ChevronRight } from "lucide-react";
import { Link } from "wouter";
import PageMeta from "@/components/PageMeta";
import SiteFooter from "@/components/SiteFooter";
import SiteHeader from "@/components/SiteHeader";
import { calculatorTools, guideArticles, hubs, type HubKey, verifiedArticles } from "@/lib/site-data";
import { keywordLandingPages } from "@/lib/keyword-pages";
import { topicAuthorityPillars } from "@/lib/topic-authority";
import "@/components/hub-specimen.css";
import "@/components/topic-authority.css";

const genericPanelCopy: Partial<Record<HubKey, { first: string; second: string; prompt: string; note: string }>> = {
  "business-software": { first: "Map the task", second: "Test the workflow", prompt: "Start with the work that needs to change.", note: "List the routine your next tool must make clearer, quicker or more reliable." },
  "ai-tools": { first: "Set the outcome", second: "Keep review in place", prompt: "Useful AI starts with a defined human decision.", note: "Choose a bounded task, then establish the checks that keep quality and privacy in view." },
  "free-tools": { first: "Enter your figures", second: "Read the limits", prompt: "A calculation is most useful when its assumptions are visible.", note: "Use your own figures, then treat the result as a starting point for the next decision." },
  "business-guides": { first: "Define the decision", second: "Choose a next step", prompt: "A practical guide should move work forward.", note: "Begin with the decision in front of you, not a list of tools or trends." },
};

export default function HubPage({ hubKey }: { hubKey: HubKey }) {
  const hub = hubs[hubKey];
  const isTools = hubKey === "free-tools";
  const isGuides = hubKey === "business-guides";
  const isReviews = hubKey === "reviews";
  const isComparisons = hubKey === "comparisons";
  const isGenericHub = !isReviews && !isComparisons;
  const editorialBatch = verifiedArticles.filter((article) => hubKey === "reviews" ? article.kind === "Review" : hubKey === "comparisons" ? article.kind === "Comparison" : false);
  const keywordBatch = keywordLandingPages.filter((page) => page.hubPath === hub.path);
  const displayedKeywordBatch = keywordBatch.slice(0, 12);
  const authorityPillars = topicAuthorityPillars.filter((pillar) => pillar.hubPath === hub.path);
  const specimenTitle = isReviews ? "Read the product page with a checklist." : "Put the workflows side by side.";
  const specimenLabel = isReviews ? "SOURCE / CHECK / FIT" : "OPTION A / OPTION B / DECISION";
  const panel = genericPanelCopy[hubKey];
  return <div className="site-shell page-shell"><PageMeta title={hub.title} path={hub.path} description={hub.description} /><SiteHeader /><main id="main-content">
    <section className={`page-hero hub-hero ${isReviews ? "review-hub-hero" : isComparisons ? "comparison-hub-hero" : ""}`}><div className="breadcrumb"><Link href="/">Home</Link><ChevronRight size={14} /><span>{hub.title}</span></div><div className="hub-hero-grid"><div><div className="page-signal-bar"><span>SECTION / 0{hub.items.length}</span><i /><span>Decision platform</span></div><span className="eyebrow">{hub.eyebrow}</span><h1>{hub.title} <em>for the work.</em></h1><p>{hub.description}</p></div>{isGenericHub && panel ? <div className="hub-specimen generic-specimen" aria-label="Decision guide"><div className="specimen-topline"><span>DECISION INDEX</span><i /><b>01</b></div><div className="generic-specimen-grid"><div><span>01 / START</span><b>{panel.first}</b></div><i /><div><span>02 / MOVE</span><b>{panel.second}</b></div></div><p className="specimen-prompt">{panel.prompt}</p></div> : (isReviews || isComparisons) && <div className={`hub-specimen ${isReviews ? "review-specimen" : "comparison-specimen"}`} aria-hidden="true"><div className="specimen-topline"><span>{specimenLabel}</span><i /><b>01</b></div>{isReviews ? <><div className="source-window"><span>OFFICIAL PAGE</span><b>Product scope</b><i /><p>Check the claim before you rely on it.</p></div><div className="source-window offset"><span>YOUR WORKFLOW</span><b>Fit test</b><i /><p>Map the task, plan and people involved.</p></div></> : <><div className="comparison-window"><span>OPTION A</span><b>Workflow / plan / checks</b></div><div className="comparison-divider"><i /><span>WEIGH THE JOB</span><i /></div><div className="comparison-window"><span>OPTION B</span><b>Workflow / plan / checks</b></div></>}<p>{specimenTitle}</p></div>}</div></section>
    <section className={`hub-content section ${isReviews ? "review-collection" : isComparisons ? "comparison-collection" : ""}`}><div className="hub-intro"><span>{isReviews ? "Review framework" : isComparisons ? "Comparison framework" : "Explore"}</span><p>{isReviews ? "A product page is evidence, not a verdict. Start with the stated scope, then test the plan, workflow and verification questions that matter to your business." : isComparisons ? "A useful comparison gives both options the same test: the job, the people, the current plan, the data and the implementation work." : "Use these sections as a starting point. Check current product information directly with a provider before making a purchase or business decision."}</p></div>{isGenericHub && panel && <div className="hub-decision-note"><span>START HERE / 01</span><p>{panel.note}</p><b>WORKFLOW FIRST</b></div>}<div className="hub-grid">{hub.items.map((item, index) => { const keywordPath = keywordLandingPages.find((page) => page.title === item.title || page.title.replace(" Software", "") === item.title)?.path; const itemPath = isTools ? calculatorTools[index]?.path ?? "/free-tools/" : isGuides ? guideArticles[index]?.path ?? "/business-guides/" : keywordPath ?? hub.path; return <article key={item.title} className={`hub-card ${isGenericHub ? "indexed-hub-card" : ""}`}><span>0{index + 1}</span><h2>{item.title}</h2><p>{item.detail}</p><Link href={itemPath}>Assess the workflow fit <ArrowUpRight size={17} /></Link></article>; })}</div></section>
    {authorityPillars.length > 0 && <section className="section authority-hub-bridge"><div><span className="eyebrow">Topic pathways</span><h2>Follow the related <em>decision paths.</em></h2><p>These pillars connect the category to adjacent work, supporting tools, practical guides and evidence-led evaluation routes.</p></div><div>{authorityPillars.map((pillar) => <Link href={`/topic-authority/#${pillar.slug}`} key={pillar.slug}><span>{pillar.index}</span><b>{pillar.title}</b><p>{pillar.summary}</p><ArrowUpRight size={17} /></Link>)}</div></section>}
    {keywordBatch.length > 0 && <section className="section verified-batch"><div className="verified-batch-head"><div><span className="eyebrow">Category pages</span><h2>Explore the work <em>behind the category.</em></h2></div><p>These focused pages use the same practical framework: define the job, check the workflow and test the option using real work. {keywordBatch.length > displayedKeywordBatch.length ? `The first ${displayedKeywordBatch.length} of ${keywordBatch.length} pages are shown here; use search or a related-page network to continue exploring.` : ""}</p></div><div className="verified-article-grid">{displayedKeywordBatch.map((page, index) => <Link href={page.path} key={page.slug} className="verified-article-card"><div><span>0{index + 1}</span><b>Category</b></div><h3>{page.title}</h3><p>{page.description}</p><strong>Open the category guide <ArrowUpRight size={16} /></strong></Link>)}</div></section>}
    {editorialBatch.length > 0 && <section className={`section verified-batch ${isReviews ? "review-batch" : "comparison-batch"}`}><div className="verified-batch-head"><div><span className="eyebrow">Verified collection</span><h2>{isReviews ? <>Read the product page <em>with a checklist.</em></> : <>Put the workflows <em>side by side.</em></>}</h2></div><p>{isReviews ? "Each review links its factual product-scope statements to an official source, then gives readers a focused set of checks for finding a practical fit." : "Each comparison frames a decision around the real work involved, not a generic winner, permanent pricing claim or unverified feature list."}</p></div><div className="verified-article-grid">{editorialBatch.map((article, index) => <Link href={article.path} key={article.slug} className="verified-article-card"><div><span>0{index + 1}</span><b>{article.kind}</b></div><h3>{article.title}</h3><p>{article.description}</p><strong>{isReviews ? "Open the review checklist" : "Open the comparison framework"} <ArrowUpRight size={16} /></strong></Link>)}</div></section>}
    {isTools && <section className="section tool-callout"><div><span className="eyebrow">Implemented calculators</span><h2>Useful inputs. Transparent maths.</h2><p>These tools calculate in your browser. They provide estimates for planning, not accounting, tax or legal advice.</p></div><div className="tool-callout-list">{calculatorTools.map((tool) => <Link href={tool.path} key={tool.slug}><strong>{tool.title}</strong><span>{tool.detail}</span><ArrowUpRight size={17} /></Link>)}</div></section>}
  </main><SiteFooter /></div>;
}
