/** Editorial Terminal: calm long-form policy and company pages with truthful, succinct content. */
import { ChevronRight, Mail } from "lucide-react";
import { Link } from "wouter";
import PageMeta from "@/components/PageMeta";
import SiteFooter from "@/components/SiteFooter";
import SiteHeader from "@/components/SiteHeader";

const pages: Record<string, { title: string; description: string; sections: { heading: string; paragraphs: string[] }[] }> = {
  about: { title: "About DigitalSolutions.cv", description: "The purpose and editorial approach of DigitalSolutions.cv, a practical technology resource.", sections: [{ heading: "What DigitalSolutions.cv is for", paragraphs: ["DigitalSolutions.cv is a practical technology and business resource for small-business owners, independent professionals, start-ups and teams.", "The site helps readers understand software, AI tools and everyday digital tasks through clear explanations, useful comparisons and practical guides."] }, { heading: "What we cover", paragraphs: ["Our coverage includes business software, AI tools, free online business tools, software reviews, software comparisons, productivity, digital marketing, cybersecurity and practical business technology guides."] }, { heading: "How we approach content", paragraphs: ["We aim for clear language, relevant context and examples that help readers evaluate their options. Information that can change, including features and pricing, should be checked before publication.", "We do not claim first-hand experience, partnerships, certifications or professional credentials unless they are clearly evidenced."] }, { heading: "Contact", paragraphs: ["For questions, corrections or suggestions, email info@digitalsolutions.cv or visit the Contact page."] }] },
  contact: { title: "Contact DigitalSolutions.cv", description: "Contact DigitalSolutions.cv with corrections, suggestions, questions and business enquiries.", sections: [{ heading: "Email", paragraphs: ["Have a question, suggestion or business enquiry? Get in touch at info@digitalsolutions.cv."] }, { heading: "Corrections and updates", paragraphs: ["If you spot an outdated feature, price, link or explanation, include the page URL and explain what should be checked. Information that changes over time will be reviewed before being updated."] }, { heading: "Business enquiries", paragraphs: ["For advertising, affiliate or partnership enquiries, identify the organisation, proposed relationship and relevant website or product. Commercial relationships will be disclosed where applicable."] }] },
  "editorial-policy": { title: "Editorial Policy", description: "How DigitalSolutions.cv approaches clear, practical and transparent editorial content.", sections: [{ heading: "Practical, verifiable content", paragraphs: ["DigitalSolutions.cv aims to explain software, AI tools and business technology in clear language. We aim to separate useful guidance from promotional claims and to check time-sensitive information before publishing it."] }, { heading: "Corrections", paragraphs: ["Readers can send corrections or source suggestions to info@digitalsolutions.cv. We will review factual corrections and update relevant content when appropriate."] }, { heading: "Commercial relationships", paragraphs: ["Content may include affiliate links or advertising in future. Where this is the case, the relationship will be disclosed clearly and content will remain the priority."] }] },
  "privacy-policy": { title: "Privacy Policy", description: "Privacy information for visitors to DigitalSolutions.cv.", sections: [{ heading: "This policy", paragraphs: ["This page provides general privacy information for visitors to DigitalSolutions.cv. It should be reviewed and updated if the site begins collecting personal data through forms, accounts, analytics or other services."] }, { heading: "Contact", paragraphs: ["For privacy questions about this site, email info@digitalsolutions.cv."] }] },
  "cookie-policy": { title: "Cookie Policy", description: "Cookie information for visitors to DigitalSolutions.cv.", sections: [{ heading: "This policy", paragraphs: ["This page explains that cookie use should be reviewed when services such as analytics, advertising or embedded third-party content are enabled. It is not a substitute for a configuration-specific policy."] }, { heading: "Future updates", paragraphs: ["If cookies are added through an external service, this policy and the visitor controls should be updated to reflect the service accurately."] }] },
  "terms-conditions": { title: "Terms & Conditions", description: "General terms for use of DigitalSolutions.cv.", sections: [{ heading: "General information", paragraphs: ["DigitalSolutions.cv provides general information and browser-based planning tools. Content is not professional legal, financial, tax or accounting advice, and readers should obtain appropriate advice for their circumstances."] }, { heading: "Accuracy and availability", paragraphs: ["Information may change and should be checked with the relevant provider or authority before acting on it."] }] },
  "affiliate-disclosure": { title: "Affiliate Disclosure", description: "How DigitalSolutions.cv will disclose affiliate relationships.", sections: [{ heading: "Affiliate links", paragraphs: ["DigitalSolutions.cv may use affiliate links in future. If a link may result in a commission, the relationship will be disclosed clearly on or near the relevant content."] }, { heading: "Editorial independence", paragraphs: ["The existence of an affiliate relationship does not remove the need for content to be useful, clear and transparent."] }] },
  "advertising-disclosure": { title: "Advertising Disclosure", description: "How DigitalSolutions.cv will distinguish advertising from editorial content.", sections: [{ heading: "Clear labelling", paragraphs: ["If advertising or sponsored content is introduced, it should be visibly distinguished from editorial content and should not be made to look like navigation or a recommendation."] }] },
};

export default function StaticPage({ pageKey }: { pageKey: string }) {
  const page = pages[pageKey] ?? pages.about;
  const path = `/${pageKey}/`;
  const mailto = pageKey === "contact" || pageKey === "about";
  const displayHeading = pageKey === "contact" ? <>Contact with <em>context.</em></> : pageKey === "about" ? <>A practical <em>decision desk.</em></> : <>{page.title}<em>.</em></>;
  const signalLabel = pageKey === "contact" ? "Contact desk / 01" : pageKey === "about" ? "Purpose / 01" : "DigitalSolutions.cv / Policy";
  return <div className="site-shell page-shell"><PageMeta title={page.title} path={path} description={page.description} /><SiteHeader /><main id="main-content"><section className="page-hero static-hero"><div className="breadcrumb"><Link href="/">Home</Link><ChevronRight size={14} /><span>{page.title}</span></div><div className="page-signal-bar"><span>DS / GLOBAL</span><i /><span>Decision notes</span></div><span className="eyebrow">{signalLabel}</span><h1>{displayHeading}</h1><p>{page.description}</p></section><article className="static-content">{page.sections.map((section, index) => <section key={section.heading}><span className="content-index">0{index + 1}</span><h2>{section.heading}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph}>{mailto && paragraph.includes("info@digitalsolutions.cv") ? <><a className="inline-email" href="mailto:info@digitalsolutions.cv"><Mail size={16} />info@digitalsolutions.cv</a>{paragraph.replace("info@digitalsolutions.cv", "")}</> : paragraph}</p>)}</section>)}</article></main><SiteFooter /></div>;
}
