import { ArrowDownRight, ArrowUpRight, CheckCircle2, ChevronRight, Compass, Network, Route, SearchCheck } from "lucide-react";
import { Link } from "wouter";
import PageMeta from "@/components/PageMeta";
import SiteFooter from "@/components/SiteFooter";
import SiteHeader from "@/components/SiteHeader";
import { keywordLandingPages } from "@/lib/keyword-pages";
import { clusterTopicLabels, topicAuthorityPillars } from "@/lib/topic-authority";
import "@/components/topic-authority.css";
import "@/components/topic-authority-variations.css";

export default function TopicAuthorityPage() {
  const totalClusters = new Set(keywordLandingPages.map((page) => page.cluster ?? "legacy-general")).size;
  return <div className="site-shell page-shell authority-page"><PageMeta title="Topic Authority Map" path="/topic-authority/" description="Explore DigitalSolutions.cv’s connected decision pillars for business software, AI, practical tools, reviews, comparisons and business guides." /><SiteHeader /><main id="main-content">
    <section className="authority-hero"><div className="authority-hero-inner"><div className="breadcrumb"><Link href="/">Home</Link><ChevronRight size={14} /><span>Topic authority map</span></div><div className="authority-hero-grid"><div><span className="eyebrow"><Compass size={15} /> Topic authority / connected decisions</span><h1>Start with the <em>work.</em><br />Follow the topic.</h1><p>DigitalSolutions.cv connects software, tools, guides and comparisons around the decisions businesses return to: revenue, customers, operations, growth, people, knowledge and practical work.</p></div><aside className="authority-index-panel" aria-label="Content coverage"><div><span>AUTHORITY INDEX</span><b>01</b></div><article><strong>{keywordLandingPages.length}</strong><span>CONNECTED CATEGORY PAGES</span></article><article><strong>{totalClusters}</strong><span>TOPIC CLUSTERS</span></article><article><strong>{topicAuthorityPillars.length}</strong><span>DECISION PILLARS</span></article></aside></div></div></section>
    <section className="authority-routebar"><div><span>01</span><b>Choose the business decision</b></div><i /><div><span>02</span><b>Open the relevant pillar</b></div><i /><div><span>03</span><b>Continue through a useful pathway</b></div></section>
    <section className="authority-layout"><aside className="authority-rail"><span>PILLAR INDEX</span>{topicAuthorityPillars.map((pillar) => <a key={pillar.slug} href={`#${pillar.slug}`}><b>{pillar.index}</b>{pillar.title}</a>)}</aside><div className="authority-content"><section className="authority-intro"><div><span>HOW TO USE THIS MAP</span><h2>Topic depth without dead ends.</h2></div><p>Every pillar begins with an actual work decision, then connects the supporting categories, practical guides, tools and evaluations that can help a visitor move forward. The map is a discovery structure, not a ranking or product endorsement.</p></section>{topicAuthorityPillars.map((pillar, pillarIndex) => {
      const clusterCards = pillar.clusters.map((cluster) => ({ cluster, pages: keywordLandingPages.filter((page) => (page.cluster ?? "legacy-general") === cluster) })).filter((item) => item.pages.length);
      const featured = pillar.featuredSlugs.map((slug) => keywordLandingPages.find((page) => page.slug === slug)).filter((page): page is NonNullable<typeof page> => Boolean(page)).slice(0, 4);
      const visualVariant = ["ledger", "window", "signal"][pillarIndex % 3];
      return <section className={`authority-pillar authority-pillar-${visualVariant}`} id={pillar.slug} key={pillar.slug}><div className="pillar-head"><div><span>{pillar.index} / {pillar.eyebrow}</span><h2>{pillar.title}</h2></div><p>{pillar.summary}</p></div><div className="pillar-cluster-grid">{clusterCards.map(({ cluster, pages }, index) => <Link href={pages[0].path} key={cluster} className="pillar-cluster-card"><span>0{index + 1} / {pages.length} PAGES</span><h3>{clusterTopicLabels[cluster] ?? cluster}</h3><p>Begin with {pages[0].title} to trace this decision path.</p><b>Trace this topic <ArrowUpRight size={15} /></b></Link>)}</div>{featured.length > 0 && <div className="pillar-featured"><div><span>CORE ROUTES</span><p>Use these pages to enter the pillar through a specific work question.</p></div><div>{featured.map((page) => <Link href={page.path} key={page.slug}><span>{page.title}</span><ArrowDownRight size={16} /></Link>)}</div></div>}</section>;
    })}</div></section>
    <section className="authority-principles"><div><span>EDITORIAL METHOD</span><h2>Useful context before recommendation.</h2></div><div className="authority-principle-grid"><article><SearchCheck size={20} /><h3>Define the decision</h3><p>Start with the routine, people, information and outcome that need to become clearer.</p></article><article><Network size={20} /><h3>Follow connected context</h3><p>Use the pillar pathways to discover related category pages without treating every tool as interchangeable.</p></article><article><Route size={20} /><h3>Test the actual fit</h3><p>Compare options against the same workflow and confirm current product details directly with providers.</p></article></div></section>
    <section className="authority-callout"><CheckCircle2 size={21} /><p><b>Authority in practice:</b> each page links to its topic pathway, related content is grouped by practical decision, and named product examples are review shortlists rather than unverified ratings or claims.</p><Link href="/business-software/">Map a business software decision <ArrowUpRight size={16} /></Link></section>
  </main><SiteFooter /></div>;
}
