/** Editorial Terminal: clear, practical calculator controls with readable assumptions and no fake results. */
import { useEffect, useMemo, useState } from "react";
import "@/components/calculator-currency.css";

export type CalculatorKind = "vat" | "sales-tax" | "margin" | "break-even" | "freelance" | "salary" | "take-home" | "loan" | "roi" | "commission";
type CalculatorPanelProps = { kind: CalculatorKind };

const CURRENCY_PREFERENCE_KEY = "digitalsolutions.display-currency";
const currencies = [{ code: "USD", label: "USD — US Dollar" }, { code: "EUR", label: "EUR — Euro" }, { code: "GBP", label: "GBP — Pound Sterling" }, { code: "CAD", label: "CAD — Canadian Dollar" }, { code: "AUD", label: "AUD — Australian Dollar" }, { code: "INR", label: "INR — Indian Rupee" }, { code: "JPY", label: "JPY — Japanese Yen" }];
const currencyCodes = new Set(currencies.map((item) => item.code));
const number = new Intl.NumberFormat("en", { maximumFractionDigits: 2 });
const toNumber = (value: string) => Math.max(0, Number(value) || 0);

function readCurrencyPreference() { try { const savedCurrency = window.localStorage.getItem(CURRENCY_PREFERENCE_KEY); return savedCurrency && currencyCodes.has(savedCurrency) ? savedCurrency : "USD"; } catch { return "USD"; } }
function Field({ label, value, onChange, suffix, hint }: { label: string; value: string; onChange: (value: string) => void; suffix: string; hint?: string }) { return <label className="field-label"><span>{label}</span><div className="field-control"><input inputMode="decimal" value={value} onChange={(event) => onChange(event.target.value)} aria-describedby={hint ? `${label.replaceAll(" ", "-")}-hint` : undefined} /><b>{suffix}</b></div>{hint && <small id={`${label.replaceAll(" ", "-")}-hint`}>{hint}</small>}</label>; }

export default function CalculatorPanel({ kind }: CalculatorPanelProps) {
  const [values, setValues] = useState<Record<string, string>>({ amount: "100", rate: "20", revenue: "1000", cost: "650", fixed: "1000", price: "50", variable: "20", income: "40000", days: "220", holiday: "28", hours: "7.5", expenses: "5000", deduction: "20", loan: "25000", loanRate: "8", term: "5", investment: "1000", returnValue: "1400", sales: "10000", commissionRate: "10" });
  const [vatMode, setVatMode] = useState<"add" | "remove">("add");
  const [currency, setCurrency] = useState(readCurrencyPreference);
  const money = useMemo(() => new Intl.NumberFormat(undefined, { style: "currency", currency, currencyDisplay: "narrowSymbol", maximumFractionDigits: currency === "JPY" ? 0 : 2 }), [currency]);
  const change = (name: string) => (value: string) => setValues((current) => ({ ...current, [name]: value }));
  useEffect(() => { try { window.localStorage.setItem(CURRENCY_PREFERENCE_KEY, currency); } catch { /* Retain calculator operation when storage is unavailable. */ } }, [currency]);

  const result = useMemo(() => {
    if (kind === "vat" || kind === "sales-tax") { const baseAmount = toNumber(values.amount); const rate = toNumber(values.rate) / 100; const net = vatMode === "add" ? baseAmount : baseAmount / (1 + rate); const gross = vatMode === "add" ? baseAmount * (1 + rate) : baseAmount; const taxLabel = kind === "vat" ? "VAT amount" : "Sales tax amount"; return { primary: money.format(gross), rows: [["Net amount", money.format(net)], [taxLabel, money.format(gross - net)], ["Gross amount", money.format(gross)]] }; }
    if (kind === "margin") { const revenue = toNumber(values.revenue); const cost = toNumber(values.cost); const profit = revenue - cost; const margin = revenue ? (profit / revenue) * 100 : 0; return { primary: `${number.format(margin)}%`, rows: [["Gross profit", money.format(profit)], ["Gross margin", `${number.format(margin)}%`], ["Revenue", money.format(revenue)]] }; }
    if (kind === "break-even") { const fixed = toNumber(values.fixed); const price = toNumber(values.price); const variable = toNumber(values.variable); const contribution = price - variable; const units = contribution > 0 ? Math.ceil(fixed / contribution) : 0; return { primary: contribution > 0 ? `${number.format(units)} units` : "Add a positive contribution", rows: [["Break-even units", contribution > 0 ? number.format(units) : "—"], ["Break-even revenue", contribution > 0 ? money.format(units * price) : "—"], ["Contribution per unit", money.format(contribution)]] }; }
    if (kind === "freelance") { const income = toNumber(values.income); const expenses = toNumber(values.expenses); const days = Math.max(1, toNumber(values.days) - toNumber(values.holiday)); const hours = Math.max(0.25, toNumber(values.hours)); const daily = (income + expenses) / days; return { primary: money.format(daily / hours), rows: [["Suggested daily rate", money.format(daily)], ["Suggested hourly rate", money.format(daily / hours)], ["Available billing days", number.format(days)]] }; }
    if (kind === "salary") { const income = toNumber(values.income); const days = Math.max(1, toNumber(values.days)); const hours = Math.max(0.25, toNumber(values.hours)); return { primary: money.format(income / 12), rows: [["Annual salary", money.format(income)], ["Monthly gross pay", money.format(income / 12)], ["Hourly gross rate", money.format(income / (days * hours))]] }; }
    if (kind === "take-home") { const income = toNumber(values.income); const deduction = toNumber(values.deduction) / 100; const net = income * (1 - deduction); return { primary: money.format(net / 12), rows: [["Gross annual income", money.format(income)], ["Indicative deductions", money.format(income - net)], ["Monthly take-home pay", money.format(net / 12)]] }; }
    if (kind === "loan") { const loan = toNumber(values.loan); const rate = toNumber(values.loanRate) / 1200; const periods = Math.max(1, toNumber(values.term) * 12); const monthly = rate > 0 ? loan * (rate * ((1 + rate) ** periods)) / (((1 + rate) ** periods) - 1) : loan / periods; return { primary: money.format(monthly), rows: [["Monthly repayment", money.format(monthly)], ["Total repayment", money.format(monthly * periods)], ["Indicative interest", money.format((monthly * periods) - loan)]] }; }
    if (kind === "roi") { const investment = toNumber(values.investment); const returnValue = toNumber(values.returnValue); const net = returnValue - investment; const roi = investment ? (net / investment) * 100 : 0; return { primary: `${number.format(roi)}%`, rows: [["Investment", money.format(investment)], ["Net return", money.format(net)], ["ROI", `${number.format(roi)}%`]] }; }
    const sales = toNumber(values.sales); const rate = toNumber(values.commissionRate) / 100; const commission = sales * rate; return { primary: money.format(commission), rows: [["Sales amount", money.format(sales)], ["Commission rate", `${number.format(rate * 100)}%`], ["Indicative commission", money.format(commission)]] };
  }, [currency, kind, money, values, vatMode]);

  const taxMode = kind === "vat" || kind === "sales-tax";
  return <div className="calculator-panel"><div className="calculator-inputs"><label className="currency-selector"><span>Display currency<small>Your preference is saved locally and used across all calculators.</small></span><select value={currency} onChange={(event) => setCurrency(event.target.value)} aria-label="Display currency">{currencies.map((item) => <option value={item.code} key={item.code}>{item.label}</option>)}</select></label>
    {taxMode && <><div className="segmented" aria-label="Tax calculation method"><button className={vatMode === "add" ? "selected" : ""} type="button" onClick={() => setVatMode("add")}>Add tax</button><button className={vatMode === "remove" ? "selected" : ""} type="button" onClick={() => setVatMode("remove")}>Remove tax</button></div><Field label={vatMode === "add" ? "Net amount" : "Gross amount"} value={values.amount} onChange={change("amount")} suffix={currency} /><Field label={kind === "vat" ? "VAT rate" : "Sales tax rate"} value={values.rate} onChange={change("rate")} suffix="%" /></>}
    {kind === "margin" && <><Field label="Revenue" value={values.revenue} onChange={change("revenue")} suffix={currency} /><Field label="Cost" value={values.cost} onChange={change("cost")} suffix={currency} /></>}
    {kind === "break-even" && <><Field label="Fixed costs" value={values.fixed} onChange={change("fixed")} suffix={currency} /><Field label="Price per unit" value={values.price} onChange={change("price")} suffix={currency} /><Field label="Variable cost per unit" value={values.variable} onChange={change("variable")} suffix={currency} /></>}
    {kind === "freelance" && <><Field label="Desired annual income" value={values.income} onChange={change("income")} suffix={currency} /><Field label="Annual business expenses" value={values.expenses} onChange={change("expenses")} suffix={currency} /><Field label="Working days per year" value={values.days} onChange={change("days")} suffix="days" /><Field label="Holiday days" value={values.holiday} onChange={change("holiday")} suffix="days" /><Field label="Working hours per day" value={values.hours} onChange={change("hours")} suffix="hours" /></>}
    {kind === "salary" && <><Field label="Annual salary" value={values.income} onChange={change("income")} suffix={currency} /><Field label="Working days per year" value={values.days} onChange={change("days")} suffix="days" /><Field label="Working hours per day" value={values.hours} onChange={change("hours")} suffix="hours" /></>}
    {kind === "take-home" && <><Field label="Gross annual income" value={values.income} onChange={change("income")} suffix={currency} /><Field label="Indicative deduction rate" value={values.deduction} onChange={change("deduction")} suffix="%" /></>}
    {kind === "loan" && <><Field label="Loan amount" value={values.loan} onChange={change("loan")} suffix={currency} /><Field label="Annual interest rate" value={values.loanRate} onChange={change("loanRate")} suffix="%" /><Field label="Loan term" value={values.term} onChange={change("term")} suffix="years" /></>}
    {kind === "roi" && <><Field label="Investment" value={values.investment} onChange={change("investment")} suffix={currency} /><Field label="Return" value={values.returnValue} onChange={change("returnValue")} suffix={currency} /></>}
    {kind === "commission" && <><Field label="Sales amount" value={values.sales} onChange={change("sales")} suffix={currency} /><Field label="Commission rate" value={values.commissionRate} onChange={change("commissionRate")} suffix="%" /></>}
  </div><output className="calculator-result" aria-live="polite"><span>Indicative result · {currency}</span><strong>{result.primary}</strong><div>{result.rows.map(([label, value]) => <p key={label}><span>{label}</span><b>{value}</b></p>)}</div></output></div>;
}
