import { ArrowUpRight } from "lucide-react";
import { Link } from "wouter";

export const crmSoftwareComparisonFaqs = [
  { question: "What is the best way to compare CRM software?", answer: "Compare CRM software by giving every option the same realistic customer scenario. Test how a new contact is captured, who owns the next action, how a deal moves through stages, what context survives a hand-off and how the team reviews an outcome. Then verify the provider's current plan terms and implementation requirements." },
  { question: "What should be included in a CRM software comparison?", answer: "A useful CRM software comparison covers the workflow, contact and company records, pipeline structure, activity history, ownership, reporting, permissions, integrations, onboarding effort, data migration and the provider's current pricing and plan limits. A long feature list alone does not show whether a team can run the system consistently." },
  { question: "How do CRM pricing plans affect a comparison?", answer: "Entry pricing is only a starting reference. Check which plan includes the users, pipelines, automation, reports, permissions, support, integrations and storage your scenario requires. Confirm billing cadence, currency, taxes, add-ons and onboarding requirements directly with the provider before you compare total implementation cost." },
  { question: "Should a small team choose a free CRM first?", answer: "A free CRM can be a sensible starting point when its included users and core workflow match the immediate job. Establish a review point before more records, hand-offs, reporting needs or connections make the current scope unsuitable. A free option should be tested with live work rather than treated as permanently sufficient." },
  { question: "How long should a CRM trial take?", answer: "Use enough time to run one complete customer scenario with the people who will own the system. The goal is not to explore every feature; it is to test whether contact context, next actions, hand-offs and reporting are clear in normal work. Record unanswered questions before moving from trial to implementation." },
] as const;

export function CrmComparisonDirectAnswer() {
  return <section className="crm-compare-direct-answer" aria-labelledby="crm-software-comparison-answer"><span>DIRECT ANSWER / 01</span><p id="crm-software-comparison-answer"><strong>A CRM software comparison should test each option against the same customer workflow, not just the longest feature list. Compare how a team captures context, assigns ownership, moves an opportunity forward and reviews results—then verify the current plan, price, permissions, integrations and implementation requirements directly with each provider.</strong></p></section>;
}

export function CrmComparisonAeo() {
  return <section className="crm-compare-aeo" aria-label="CRM software comparison guide">
    <div className="crm-compare-evidence">
      <div><span>PROVIDER REFERENCE / CHECK LIVE TERMS</span><h2>Published entry points are useful context, not a universal CRM verdict.</h2></div>
      <p>Pricing, included features and regional availability can change. The references below are official provider-page examples, selected to show how a CRM comparison should distinguish between entry position and operating fit. Confirm local currency, taxes, plan limits, onboarding, security, data handling and integrations directly with each provider.</p>
    </div>

    <section className="crm-compare-section-intro"><span>02 / PROVIDER REFERENCE TABLE</span><h2>Compare the same CRM job before you compare the provider.</h2><p>Each platform can be evaluated using one scenario: a customer enquiry, the information that needs recording, the person accountable for the next action and the evidence that the opportunity has progressed or needs review.</p></section>
    <div className="crm-compare-table-wrap"><table><thead><tr><th>Software name</th><th>Useful comparison lens</th><th>Current entry reference</th><th>Question to verify</th></tr></thead><tbody>
      <tr><td><a href="https://www.hubspot.com/pricing/sales" target="_blank" rel="noreferrer">HubSpot Sales Hub <ArrowUpRight size={13} /></a></td><td>Customer platform route for teams considering a free starting point and broader connected hubs.</td><td>Free is stated for up to two users; annual Starter is displayed from $7 per seat/month.</td><td>Which pipeline, automation, reporting, onboarding and integration requirements sit within the selected tier?</td></tr>
      <tr><td><a href="https://www.pipedrive.com/en/pricing" target="_blank" rel="noreferrer">Pipedrive <ArrowUpRight size={13} /></a></td><td>Dedicated sales workspace for teams comparing deal-pipeline and activity-led routines.</td><td>Annual Lite is displayed at US$14 per seat/month, with a 14-day trial stated.</td><td>Do the automation, reporting, security or add-on needs begin above the chosen plan?</td></tr>
      <tr><td><a href="https://www.zoho.com/en-us/crm/zohocrm-pricing.html" target="_blank" rel="noreferrer">Zoho CRM <ArrowUpRight size={13} /></a></td><td>CRM option for teams comparing free usage with broader configurable system requirements.</td><td>The free edition is displayed for three users; paid prices and currency presentation vary by location.</td><td>Which local edition, tax treatment, integrations and workflow limits apply to the intended use?</td></tr>
    </tbody></table></div>

    <section className="crm-compare-scenario" role="img" aria-label="CRM comparison workflow showing the same customer scenario used to test capture, ownership, hand-off and review across every provider"><div className="crm-compare-scenario-head"><span>SAME-SCENARIO TEST / 03</span><b>CAPTURE · OWN · HAND-OFF · REVIEW</b></div><div className="crm-compare-scenario-track"><article><span>01 / CAPTURE</span><strong>New customer enquiry</strong><p>Can the source, customer need and essential context enter cleanly?</p></article><i /><article><span>02 / OWN</span><strong>Next action assigned</strong><p>Can the team see the responsible person, timing and reason to follow up?</p></article><i /><article><span>03 / HAND-OFF</span><strong>Context moves intact</strong><p>Can a second person understand the customer without rebuilding the history?</p></article><i /><article><span>04 / REVIEW</span><strong>Outcome is visible</strong><p>Can the team inspect progress, exceptions and learning from the result?</p></article></div><p>Run this one scenario through every shortlisted CRM. The objective is comparable evidence, not a generic product score.</p></section>

    <section className="crm-compare-copy"><div><span>04 / COMPARISON METHOD</span><h2>A CRM software comparison becomes more useful when the team records evidence, not impressions.</h2></div><div><p>Start by describing the operating problem in plain language. A sales team might be losing track of enquiries; an account team might need cleaner ownership during a hand-off; a founder might need one reliable view of active opportunities. The comparison should make that problem measurable through a shared test, rather than letting each provider be judged against a different, shifting expectation.</p><p>Keep the first scorecard narrow. Assess whether each product supports the contact and company record, opportunity stage, activity history, accountable owner and next action required by the chosen scenario. Then examine the conditions that decide whether the system remains usable: permissions, imports, reporting, integrations, mobile access, data quality controls, support, implementation effort and the routine the team will use to keep records current.</p><p>Use the provider reference table as a prompt to verify terms, not as a purchasing recommendation. Entry-level pricing can be helpful context, yet the decisive cost may depend on users, billing cadence, currencies, taxes, onboarding, features, add-ons and the work needed to adopt the system. Note the current provider evidence beside the scenario result so the team can see assumptions before deciding.</p><p>Related tools matter only when they create a reliable hand-off. For example, connect <Link href="/email-marketing-software/">email marketing software</Link> when the source, consent, trigger and exception path are clear. Consider <Link href="/business-automation/">business automation</Link> only after the CRM record, responsible owner and review path are dependable. A connection should make a real workflow easier to operate—not hide an unclear customer process.</p></div></section>

    <section className="crm-compare-scorecard" aria-label="CRM comparison scorecard"><div><span>OPERATING FIT SCORECARD / 04</span><h2>Can every shortlisted CRM pass the same four practical checks?</h2><p>Write a short evidence note for each cell after running the scenario. If the evidence is uncertain, it becomes a trial question—not an assumed capability.</p><Link href="/crm-software-for-startups/">Explore CRM software for startups <ArrowUpRight size={16} /></Link></div><aside role="img" aria-label="CRM comparison scorecard with checks for customer record, next action, team hand-off and outcome review"><span>WORKING SCORECARD</span><div><b>01</b><p><strong>RECORD</strong>Context captured</p><i>TEST</i></div><div><b>02</b><p><strong>ACTION</strong>Owner visible</p><i>TEST</i></div><div><b>03</b><p><strong>HAND-OFF</strong>History retained</p><i>TEST</i></div><div><b>04</b><p><strong>REVIEW</strong>Outcome inspectable</p><i>TEST</i></div><em>ONE SCENARIO · SAME CRITERIA · RECORDED EVIDENCE</em></aside></section>

    <ol className="crm-compare-checks"><li><span>01</span><div><h3>Set the comparison boundary before opening a trial.</h3><p>Name the customer workflow, the people involved, the decision being improved and the information that must remain visible. This prevents a broad feature list from replacing a defined evaluation task.</p></div></li><li><span>02</span><div><h3>Use the same realistic customer record.</h3><p>Create or import an equivalent contact, company, opportunity and activity sequence in every shortlisted option. Check how clearly the system shows source context, current stage, ownership and next action.</p></div></li><li><span>03</span><div><h3>Test the team hand-off and the exception.</h3><p>Reassign the work, add a missing-data condition or change the expected path. A useful CRM does not only support the ideal flow; it helps the team identify what needs attention.</p></div></li><li><span>04</span><div><h3>Verify current provider terms before selecting.</h3><p>Confirm the exact plan, local pricing, taxes, included users, feature scope, security, integrations, support, data migration and onboarding conditions that apply to the selected configuration.</p></div></li></ol>

    <section className="crm-compare-faq" aria-labelledby="crm-software-comparison-faq"><div className="crm-compare-section-intro"><span>05 / CONVERSATIONAL ANSWERS</span><h2 id="crm-software-comparison-faq">CRM software comparison FAQs</h2><p>Use these direct answers to create a focused shortlist, run a meaningful trial and keep the decision evidence-led.</p></div><div>{crmSoftwareComparisonFaqs.map((item, index) => <article key={item.question}><span>0{index + 1}</span><h3>{item.question}</h3><p>{item.answer}</p></article>)}</div></section>
  </section>;
}
